### address insert
post http://localhost:8080/address HTTP/1.1
content-type: application/json

{
  	"StreetName": "Bograshov",
	"CityId": 1,
	"Building": 55,
	"CountryId": 367
}

### chance insert
post http://localhost:8080/chance HTTP/1.1
content-type: application/json

{
	"Address": {
      "Street": {"LocalName": "Bograshov"},
      "City": {"CityId": 1},
      "Country": {"CountryId": 367},
      "Building": 1
    },
	"Driver": {
		"MobileNum": "0544123123"
	},
	"Chance": {
		"DateStart": "7/8/2020, 11:28:42 AM"
	}
}
