### address insert
post http://localhost:8080/address HTTP/1.1
content-type: application/json

{
	"Address": {
		"StreetLocalName": "Bograshov",
		"CityId": 1,
		"CountryId": 367,
		"Building": 21
    }
}

### chance insert
post http://localhost:8080/chance HTTP/1.1
content-type: application/json

{
	"Address": {
		"StreetLocalName": "Bograshov",
		"CityId": 1,
		"CountryId": 367,
		"Building": 1
    },
	"Driver": {
		"MobileNum": "0544123123"
	},
	"Chance": {
		"DateStart": "7/8/2020, 11:28:42 AM"
	}
}
