@PORT = 8080
# @ENV = https://chance-app.herokuapp.com
@ENV = http://localhost:8080

	
### chance test
get {{ENV}}/ HTTP/1.1

### address get
post {{ENV}}/address-get HTTP/1.1
content-type: application/json

{
	"Address": {
		"StreetName": "בוגרשוב",
		"CityId": 1,
		"CountryId": 367,
		"Building": 1
    }
}

### address insert
post {{ENV}}/address HTTP/1.1
content-type: application/json

{
	"Address": {
		"StreetName": "בוגרשוב",
		"CityId": 1,
		"CountryId": 367,
		"Building": 3
    }
}

### chance insert
post {{ENV}}/chance HTTP/1.1
content-type: application/json

{
	"Address": {
		"StreetName": "תכף מפנה בבוגרשוב 55",
		"CityId": 1,
		"CountryId": 367,
		"Building": 1
    },
	"Driver": {
		"MobileNum": "0544123123"
	},
	"Chance": {
		"DateStart": "7/8/2020, 11:28:42 AM"
	}
}
