FROM node:12-alpine

ARG crypto_key=the_pwd_come_in_build_cmd_line
ARG node_env=development
ENV CRYPTO_KEY $crypto_key
ENV NODE_ENV=$node_env

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Run the image as a non-root user
# RUN adduser -D web_user
# USER web_user

EXPOSE 8080
CMD [ "node", "src/server.js" ]
