version: 2.1

jobs:
  build-and-test:
    working_directory: ~/chance-server
    docker:
      - image: cimg/node:16.13.0
      - image: postgres:12-alpine # - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ParkingTest
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: |
          psql \
          -h localhost \
          -U postgres
          -d ParkingTest \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d ParkingTest \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # - run: 
      #     name: Install Postgres Client
      #     command: "sudo npm install -g postgresql-client"
      - run: 
          name: Create a Database
          command: |  # psql -h localhost -U ${POSTGRES_USER} -c "alter user ${POSTGRES_USER} with password '${POSTGRES_PASSWORD}'"
            psql -h localhost -d ParkingTest -f ./sql/psql/schema.sql
      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run test for the application
          command: npm run test
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push web --recursive -a chance-app
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web -a chance-app

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
