version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: postgres:12-alpine
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    working_directory: ~/repo

    steps:
      - checkout
      
      # Copy psql folder to Postgres image
      # - run:
      #     name: Copy psql folder
      #     command: |
      #       docker cp ./sql/psql/ ./

      # - run:
      #     name: Start Postgres
      #     command: |
      #       /etc/init.d/postgresql start
      - run: npm install
      - run: npm test

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push web --recursive -a chance-app
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web -a chance-app

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
