version: 2.1
jobs:
  build:
    docker:
      - image: simonbor/chance-repo:db-0.0.0
        auth:
          username: simonbor
          password: $DOCKERHUB____PASSWORD
workflows:
  build-deploy:
    jobs:
      - build