version: 2.1
jobs:
  build:
    working_directory: /root
    docker:
      - image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "1234Qwer"
    steps:
      - checkout
workflows:
  build-deploy:
    jobs:
      - build