version: 2
jobs:
  build:
    working_directory: ~/chance-tmp
    docker:
      - image: docker/compose:1.22.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: folder listing for debugging
          command: ls -al
      # - run:
      #     name: docker build
      #     command: |
      #       docker build -t db -f Dockerfile.db .
      # - run:
      #     name: Create docker network
      #     command: |
      #       docker network create --subnet=172.18.0.0/16 chance-network
      # - run:
      #     name: Run db container
      #     command: |
      #       docker run -it --net chance-network --ip 172.18.0.10 --name db --restart=always -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=1234Qwer" -p 1433:1433 -d db
      # - run:
      #     name: Create database
      #     command: |
      #       docker exec -it db /opt/mssql-tools/bin/sqlcmd -U SA -P 1234Qwer -i database.sql 
      - run:
          name: Docker login
          command: |
            docker login -u $DOCKER_LOGIN $DOCKER_PASSWORD
