version: 2.1
jobs:
  build:
    working_directory: /root
    docker:
      - image: simonbor/chance-repo:db-0.0.0
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "1234Qwer"
    steps:
      - checkout
workflows:
  build-deploy:
    jobs:
      - build