version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.22.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: folder listing for debugging
          command: ls -al
      - run:
          name: docker build
          command: |
            docker build -t db -f Dockerfile.db .
