version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-deploy

jobs:
  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push --recursive -a chance-app
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release db -a chance-app
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web -a chance-app
      - run:
          name: Docker images
          command: |
            docker images
      - run:
          name: Create docker network
          command: |
            docker network create --subnet=172.18.0.0/16 chance-network
      - run:
          name: Run db container
          command: |
            set -x
            sudo docker run -it --net chance-network --ip 172.18.0.10 --name db --restart=always -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=${HEROKU_SA_PASSWORD}" -p 1433:1433 -d registry.heroku.com/chance-app/db
      - run:
          name: Run web container
          command: |
            sudo docker run -it --net chance-network --ip 172.18.0.5 --name web --restart=always -p 8080:8080 -d registry.heroku.com/chance-app/web
      # - run:
      #     name: Change SA_PASSWORD
      #     command: |
      #       docker exec -it db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "1234Qwer" -Q 'ALTER LOGIN SA WITH PASSWORD="$HEROKU_SA_PASSWORD"'
      # - run:
      #     name: Print HEROKU_SA_PASSWORD
      #     command: |
      #       echo $HEROKU_SA_PASSWORD
      - run:
          name: Create database
          command: |
            set -x
            sudo docker exec -it db /opt/mssql-tools/bin/sqlcmd -U SA -P ${HEROKU_SA_PASSWORD} -i database.sql 
