version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-deploy

jobs:
  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push --recursive -a chance-app
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release db -a chance-app
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web -a chance-app
      - run:
          name: create docker network
          command: |
            docker network create --subnet=172.18.0.0/16 chance-network
    
      - run:
          name: run db container
          command: |
          docker run -it --net chance-network --ip 172.18.0.10 --name db --restart=always -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=1234Qwer" -p 1433:1433 -d db
    