version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push web --recursive -a chance-app
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web -a chance-app

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
