truncate table auth."Role" cascade;
insert into auth."Role" ("RoleId", "RoleName")
select 1, 'Admin' union all
select 5, 'Manager' union all
select 9, 'User';

truncate table main."City" cascade;
insert into main."City" ("CityId", "Name", "LocalName")
select 1, 'Tel Aviv', 'תל אביב' union all
select 2, 'Jerusalem', 'ירושלים';

truncate table main."Street" cascade;
insert into main."Street" ("StreetId", "LocalName", "OtherNames", "CityId")
select 1, 'רדינג', null, 1 union all
select 2, 'בן הלל מרדכי', null, 1 union all
select 3, 'הררי', null, 1 union all
select 4, 'קרני יהודה', null, 1 union all
select 5, 'שמעוני', null, 1 union all
select 6, 'פיכמן', null, 1 union all
select 7, 'הברון הירש', null, 1 union all
select 8, 'בלום ליאון', null, 1 union all
select 9, 'ברש אשר', null, 1 union all
select 10, 'ברודצקי', null, 1 union all
select 11, 'נח', null, 1 union all
select 12, 'לחובר', null, 1 union all
select 13, 'סלואדור', null, 1 union all
select 14, 'הרטגלס', null, 1 union all
select 15, 'לבנון חיים', null, 1 union all
select 16, 'גרונימן', null, 1 union all
select 17, 'כפר יונה', null, 1 union all
select 18, 'פטאי יוסף', null, 1 union all
select 19, 'טורטשינר', null, 1 union all
select 20, 'צמחי היהודים', null, 1 union all
select 21, 'קרויס', null, 1 union all
select 22, 'ברודי', null, 1 union all
select 23, 'הופיין', null, 1 union all
select 24, 'בארט', null, 1 union all
select 25, 'אינשטיין', null, 1 union all
select 26, 'אוניברסיטת תל אבי', null, 1 union all
select 27, 'חי"ש', null, 1 union all
select 28, 'המשמר האזרחי', null, 1 union all
select 29, 'הנוטר', null, 1 union all
select 30, 'המתנדב', null, 1 union all
select 31, 'אפקים', null, 1 union all
select 32, 'חיל משמר', null, 1 union all
select 33, 'מגשימים', null, 1 union all
select 34, 'עלומים', null, 1 union all
select 35, 'מרדכי (מוטה) גור', null, 1 union all
select 36, 'מבטחים', null, 1 union all
select 37, 'שפיה', null, 1 union all
select 38, 'קוממיות', null, 1 union all
select 39, 'ברקאי שמואל', null, 1 union all
select 40, 'שמיר', null, 1 union all
select 41, 'ארזי יהודה', null, 1 union all
select 42, 'פרויד', null, 1 union all
select 43, 'קלוזנר', null, 1 union all
select 44, 'שבט ראובן', null, 1 union all
select 45, 'שבט גד', null, 1 union all
select 46, 'בני ישראל', null, 1 union all
select 47, 'שבט בנימין', null, 1 union all
select 48, 'שבט שמעון', null, 1 union all
select 49, 'שבט לוי', null, 1 union all
select 50, 'שבט יששכר', null, 1 union all
select 51, 'שבט יהודה', null, 1 union all
select 52, 'שבט זבולון', null, 1 union all
select 53, 'שבט דן', null, 1 union all
select 54, 'שבט אשר', null, 1 union all
select 55, 'שבט יוסף', null, 1 union all
select 56, 'רח 4222', null, 1 union all
select 57, 'ברלינר', null, 1 union all
select 58, 'ש"י', null, 1 union all
select 59, 'פראנקל', null, 1 union all
select 60, 'התנאים', null, 1 union all
select 61, 'הסבוראים', null, 1 union all
select 62, 'האמוראים', null, 1 union all
select 63, 'קרית שאול', null, 1 union all
select 64, 'רודנסקי שמואל', null, 1 union all
select 65, 'קלצ''קין', null, 1 union all
select 66, 'שד אבנר מאיר', null, 1 union all
select 67, 'קרן היסוד', null, 1 union all
select 68, 'טאגור רבינדרנארט', null, 1 union all
select 69, 'אנדרסן', null, 1 union all
select 70, 'פסטרנק אריה', null, 1 union all
select 71, 'ברגסון', null, 1 union all
select 72, 'מוריץ דניאל', null, 1 union all
select 73, 'פיליכובסקי', null, 1 union all
select 74, 'שד רוקח', null, 1 union all
select 75, 'יהודה הנשיא', null, 1 union all
select 76, 'לויטן יצחק', null, 1 union all
select 77, 'מניה וישראל', null, 1 union all
select 78, 'הרכש', null, 1 union all
select 79, 'פרופס אהרון צבי', null, 1 union all
select 80, 'רח 2203', null, 1 union all
select 81, 'אושה', null, 1 union all
select 82, 'משמר הגבול', null, 1 union all
select 83, 'אופנהיימר', null, 1 union all
select 84, 'גייגר', null, 1 union all
select 85, 'רבינא', null, 1 union all
select 86, 'רב אשי', null, 1 union all
select 87, 'ברזיל', null, 1 union all
select 88, 'אפטר יעקב', null, 1 union all
select 89, 'בורלא יהודה', null, 1 union all
select 90, 'אשכול לוי', null, 1 union all
select 91, 'עגנון ש"י', null, 1 union all
select 92, 'למדן יצחק', null, 1 union all
select 93, 'קיציס יוסף', null, 1 union all
select 94, 'בן ישי', null, 1 union all
select 95, 'קהילת סופיה', null, 1 union all
select 96, 'רוזאניס', null, 1 union all
select 97, 'מיזאן', null, 1 union all
select 98, 'רומנו', null, 1 union all
select 99, 'מנורה', null, 1 union all
select 100, 'גנתון', null, 1 union all
select 101, 'רוממה', null, 1 union all
select 102, 'מורשת', null, 1 union all
select 103, 'יפעת', null, 1 union all
select 104, 'יציץ', null, 1 union all
select 105, 'גזית', null, 1 union all
select 106, 'שדה דב', null, 1 union all
select 107, 'רפידים', null, 1 union all
select 108, 'מגדל שרשן', null, 1 union all
select 109, 'תל ברוך', null, 1 union all
select 110, 'אופיר', null, 1 union all
select 111, 'אוגרית', null, 1 union all
select 112, 'שורר חיים', null, 1 union all
select 113, 'הרבסט קרול', null, 1 union all
select 114, 'קפריסין', null, 1 union all
select 115, 'עמרי', null, 1 union all
select 116, 'בית חורון', null, 1 union all
select 117, 'בני אפרים', null, 1 union all
select 118, 'וייז ג''ורג''', null, 1 union all
select 119, 'קהילת יאסי', null, 1 union all
select 120, 'יד המעביר', null, 1 union all
select 121, 'קהילת בודפסט', null, 1 union all
select 122, 'קהילת ורשה', null, 1 union all
select 123, 'קהילת אודסה', null, 1 union all
select 124, 'קהילת קישינוב', null, 1 union all
select 125, 'קהילת טשרנוביץ', null, 1 union all
select 126, 'אמיל בריג', null, 1 union all
select 127, 'קהילת לודג''', null, 1 union all
select 128, 'הדר יוסף', null, 1 union all
select 129, 'בן זבארה', null, 1 union all
select 130, 'ברכיהו הנקדן', null, 1 union all
select 131, 'זכות משה', null, 1 union all
select 132, 'סומו יהודה', null, 1 union all
select 133, 'יוסף האפרתי', null, 1 union all
select 134, 'חופשי דוד', null, 1 union all
select 135, 'רח 579', null, 1 union all
select 136, 'קהילת לבוב', null, 1 union all
select 137, 'קהילת קרקוב', null, 1 union all
select 138, 'קהילת ביאליסטוק', null, 1 union all
select 139, 'קהילת בריסק', null, 1 union all
select 140, 'קדושי השואה', null, 1 union all
select 141, 'מבצע קדש', null, 1 union all
select 142, 'קהילת ונציה', null, 1 union all
select 143, 'קהילת סאלוניקי', null, 1 union all
select 144, 'קהילת ריגא', null, 1 union all
select 145, 'קהילת ז''יטומיר', null, 1 union all
select 146, 'קהילת פאדובה', null, 1 union all
select 147, 'קהילת פוזנא', null, 1 union all
select 148, 'קהילת קובנה', null, 1 union all
select 149, 'קהילת קיוב', null, 1 union all
select 150, 'חצור', null, 1 union all
select 151, 'קדש ברנע', null, 1 union all
select 152, 'שניר', null, 1 union all
select 153, 'קרן קיימת לישראל', null, 1 union all
select 154, 'אש שלום', null, 1 union all
select 155, 'לאה', null, 1 union all
select 156, 'אנכי', null, 1 union all
select 157, 'אלתרמן נתן', null, 1 union all
select 158, 'המאירי אביגדור', null, 1 union all
select 159, 'האוזנר דב', null, 1 union all
select 160, 'שיטרית', null, 1 union all
select 161, 'שינמן פנחס', null, 1 union all
select 162, 'אריכא יוסף', null, 1 union all
select 163, 'רקנאטי', null, 1 union all
select 164, 'פרסיץ שושנה', null, 1 union all
select 165, 'זאב', null, 1 union all
select 166, 'זליג', null, 1 union all
select 167, 'מעונות אוניברסיטה', null, 1 union all
select 168, 'מרק יעקב', null, 1 union all
select 169, 'אחימאיר אבא', null, 1 union all
select 170, 'בן יוסף שלמה', null, 1 union all
select 171, 'בית צורי אליהו', null, 1 union all
select 172, 'חכים אליהו', null, 1 union all
select 173, 'גרונר דב', null, 1 union all
select 174, 'אלקחי מרדכי', null, 1 union all
select 175, 'קשאני אליעזר', null, 1 union all
select 176, 'ברזאני משה', null, 1 union all
select 177, 'פיינשטיין', null, 1 union all
select 178, 'חביב אבשלום', null, 1 union all
select 179, 'נקר מאיר', null, 1 union all
select 180, 'וייס יעקב', null, 1 union all
select 181, 'דרזנר יחיאל', null, 1 union all
select 182, 'גליקסברג', null, 1 union all
select 183, 'שלונסקי', null, 1 union all
select 184, 'פרידלנד צבי', null, 1 union all
select 185, 'ברטונוב יהושע', null, 1 union all
select 186, 'צ''מרינסקי ברוך', null, 1 union all
select 187, 'טורקוב זיגמונד', null, 1 union all
select 188, 'מסקין אהרון', null, 1 union all
select 189, 'צה"ל', null, 1 union all
select 190, 'ברק', null, 1 union all
select 191, 'המצביאים', null, 1 union all
select 192, 'בת יפתח', null, 1 union all
select 193, 'סביון', null, 1 union all
select 194, 'נורית', null, 1 union all
select 195, 'הרדוף', null, 1 union all
select 196, 'אמנון ותמר', null, 1 union all
select 197, 'מרגנית', null, 1 union all
select 198, 'עיר שמש', null, 1 union all
select 199, 'יהונתן', null, 1 union all
select 200, 'אהוד', null, 1 union all
select 201, 'אבנר', null, 1 union all
select 202, 'יואב', null, 1 union all
select 203, 'השושנים', null, 1 union all
select 204, 'אבישי', null, 1 union all
select 205, 'שמגר', null, 1 union all
select 206, 'בניהו', null, 1 union all
select 207, 'בת חן', null, 1 union all
select 208, 'הפרסה', null, 1 union all
select 209, 'עשהאל', null, 1 union all
select 210, 'בנימין מטודלה', null, 1 union all
select 211, 'משמר הירדן', null, 1 union all
select 212, 'אלדד הדני', null, 1 union all
select 213, 'אשכנזי', null, 1 union all
select 214, 'פתחיה מרגנשבורג', null, 1 union all
select 215, 'רומנילי', null, 1 union all
select 216, 'אבן ספיר', null, 1 union all
select 217, 'תבואות הארץ', null, 1 union all
select 218, 'אליהו מפירארה', null, 1 union all
select 219, 'דילה רינה יוסף', null, 1 union all
select 220, 'חילו יצחק', null, 1 union all
select 221, 'הגולן', null, 1 union all
select 222, 'הרוגי מלכות', null, 1 union all
select 223, 'גולי קניה', null, 1 union all
select 224, 'גולי אריתראה', null, 1 union all
select 225, 'טובים עמנואל', null, 1 union all
select 226, 'נמירובר', null, 1 union all
select 227, 'לויטה', null, 1 union all
select 228, 'קרפל ליפא', null, 1 union all
select 229, 'טריטש', null, 1 union all
select 230, 'שטיינר', null, 1 union all
select 231, 'עולי הגרדום', null, 1 union all
select 232, 'מרכוס דוד', null, 1 union all
select 233, 'טבנקין יצחק', null, 1 union all
select 234, 'ניסן כהן', null, 1 union all
select 235, 'ק"ם', null, 1 union all
select 236, 'גדנ"ע', null, 1 union all
select 237, 'ביריה', null, 1 union all
select 238, 'הטית זין', null, 1 union all
select 239, 'הראל', null, 1 union all
select 240, 'עטרות', null, 1 union all
select 241, 'רבדים', null, 1 union all
select 242, 'רמות נפתלי', null, 1 union all
select 243, 'הלמד הא', null, 1 union all
select 244, 'באסולה', null, 1 union all
select 245, 'סמ משמר הירדן', null, 1 union all
select 246, 'הברזל', null, 1 union all
select 247, 'ולנברג ראול', null, 1 union all
select 248, 'רח 3412', null, 1 union all
select 249, 'הארד', null, 1 union all
select 250, 'הנחושת', null, 1 union all
select 251, 'רוזוב', null, 1 union all
select 252, 'דבורה הנביאה', null, 1 union all
select 253, 'רח 2832', null, 1 union all
select 254, 'רח 3832', null, 1 union all
select 255, 'רח 4832', null, 1 union all
select 256, 'נחלאות', null, 1 union all
select 257, 'בית אל', null, 1 union all
select 258, 'רמה', null, 1 union all
select 259, 'כיסופים', null, 1 union all
select 260, 'רביבים', null, 1 union all
select 261, 'אדירים', null, 1 union all
select 262, 'פילדלפיה', null, 1 union all
select 263, 'הצנחנים', null, 1 union all
select 264, 'אח"י דקר', null, 1 union all
select 265, 'אלמגור', null, 1 union all
select 266, 'כורזים', null, 1 union all
select 267, 'נהריים', null, 1 union all
select 268, 'מינץ בנימין', null, 1 union all
select 269, 'ענתות', null, 1 union all
select 270, 'שוהם מתתיהו', null, 1 union all
select 271, 'ויסבורג חיים', null, 1 union all
select 272, 'טולקובסקי', null, 1 union all
select 273, 'מויאל אהרון', null, 1 union all
select 274, 'בראלי', null, 1 union all
select 275, 'אבוקה', null, 1 union all
select 276, 'פומרוק יוסף', null, 1 union all
select 277, 'אמירים', null, 1 union all
select 278, 'מבוא גילת', null, 1 union all
select 279, 'מבוא גניגר', null, 1 union all
select 280, 'מבוא געתון', null, 1 union all
select 281, 'מבוא גרופית', null, 1 union all
select 282, 'הדף היומי', null, 1 union all
select 283, 'תירוש', null, 1 union all
select 284, 'סנה משה', null, 1 union all
select 285, 'כ"ג יורדי הסירה', null, 1 union all
select 286, 'התערוכה', null, 1 union all
select 287, 'ירמיהו', null, 1 union all
select 288, 'דיזנגוף', 'דיזינגוף', 1 union all
select 289, 'זכריה', null, 1 union all
select 290, 'צידון', null, 1 union all
select 291, 'שער ציון', null, 1 union all
select 292, 'הושע', null, 1 union all
select 293, 'נמל תל אביב', null, 1 union all
select 294, 'נחשון', null, 1 union all
select 295, 'חבקוק', null, 1 union all
select 296, 'נחום', null, 1 union all
select 297, 'מיכה', null, 1 union all
select 298, 'יואל הנביא', null, 1 union all
select 299, 'יחזקאל', null, 1 union all
select 300, 'מלאכי', null, 1 union all
select 301, 'עובדיה הנביא', null, 1 union all
select 302, 'סמ מיכה', null, 1 union all
select 303, 'צפניה', null, 1 union all
select 304, 'יוחנן הורקנוס', null, 1 union all
select 305, 'שמעון התרסי', null, 1 union all
select 306, 'סמ התרסי', null, 1 union all
select 307, 'אלכסנדר ינאי', null, 1 union all
select 308, 'שד נורדאו', 'נורדאו', 1 union all
select 309, 'יהושע בן נון', 'יהושוע בן נון,יהושוע,יהושע', 1 union all
select 310, 'עמוס', null, 1 union all
select 311, 'סמ עמוס', null, 1 union all
select 312, 'סוקולוב', null, 1 union all
select 313, 'סמ נורדאו', null, 1 union all
select 314, 'ישעיהו', null, 1 union all
select 315, 'חגי', null, 1 union all
select 316, 'מודיעין', null, 1 union all
select 317, 'אגריפס', null, 1 union all
select 318, 'אוסישקין', null, 1 union all
select 319, 'ארבע ארצות', null, 1 union all
select 320, 'אשתורי הפרחי', null, 1 union all
select 321, 'משעול שמידט יוסף', null, 1 union all
select 322, 'עובדיה מברטנורה', null, 1 union all
select 323, 'אלקלעי', null, 1 union all
select 324, 'השל"ה', null, 1 union all
select 325, 'עמדן', 'עמדן יעקב', 1 union all
select 326, 'איבשיץ', 'אייבשיץ', 1 union all
select 327, 'הבשן', null, 1 union all
select 328, 'יריחו', null, 1 union all
select 329, 'עין גדי', null, 1 union all
select 330, 'הגלעד', null, 1 union all
select 331, 'הר נבו', null, 1 union all
select 332, 'זנגביל', null, 1 union all
select 333, 'בזל', null, 1 union all
select 334, 'מנדלשטם', null, 1 union all
select 335, 'טהון יהושע', null, 1 union all
select 336, 'יפה נוף', null, 1 union all
select 337, 'מוצקין', null, 1 union all
select 338, 'ויתקין', null, 1 union all
select 339, 'ז''בוטינסקי', null, 1 union all
select 340, 'גריזים', null, 1 union all
select 341, 'פקיעין', null, 1 union all
select 342, 'סמ זנגביל', null, 1 union all
select 343, 'סמ מנדלשטם', null, 1 union all
select 344, 'הירקון', 'ירקון', 1 union all
select 345, 'ברון עקיבא', null, 1 union all
select 346, 'סמ נחושתן', null, 1 union all
select 347, 'שד יוצ"ר', null, 1 union all
select 348, 'זרובבל יעקב', null, 1 union all
select 349, 'בת מרים יוכבד', null, 1 union all
select 350, 'בוקשפן דוד', null, 1 union all
select 351, 'בויאר אברהם', null, 1 union all
select 352, 'דיסנצ''יק אריה', null, 1 union all
select 353, 'ארם משה', null, 1 union all
select 354, '2390', null, 1 union all
select 355, 'רח 5821', null, 1 union all
select 356, 'אגדתי ברוך', null, 1 union all
select 357, 'השחקנים', null, 1 union all
select 358, 'בינט מאיר', null, 1 union all
select 359, 'רח 2005', null, 1 union all
select 360, 'מהר"ל', null, 1 union all
select 361, 'חת"ם סופר', 'חתם סופר', 1 union all
select 362, 'לוי יצחק', null, 1 union all
select 363, 'התניא', null, 1 union all
select 364, 'פרנקפורט', null, 1 union all
select 365, 'וילנא', null, 1 union all
select 366, 'פראג', null, 1 union all
select 367, 'הלפרין', null, 1 union all
select 368, 'זלטופולסקי', null, 1 union all
select 369, 'בן יהודה', null, 1 union all
select 370, 'מאנגר איציק', null, 1 union all
select 371, 'סמ החובבים', null, 1 union all
select 372, 'יוסט', null, 1 union all
select 373, 'בחור אליהו', null, 1 union all
select 374, 'עמנואל הרומי', null, 1 union all
select 375, 'אמסטרדם', null, 1 union all
select 376, 'קלונימוס', null, 1 union all
select 377, 'עזריה מן האדומים', null, 1 union all
select 378, 'קורדובה', null, 1 union all
select 379, 'וורמיזה', null, 1 union all
select 380, 'סמ נ"ס', null, 1 union all
select 381, 'הקליר', 'קליר', 1 union all
select 382, 'אלחריזי', null, 1 union all
select 383, 'בן עזרא', null, 1 union all
select 384, 'הפרדס', null, 1 union all
select 385, 'שמואל הנגיד', null, 1 union all
select 386, 'הדסה', null, 1 union all
select 387, 'יודפת', null, 1 union all
select 388, 'גוש חלב', null, 1 union all
select 389, 'באר טוביה', null, 1 union all
select 390, 'חולדה', null, 1 union all
select 391, 'מצדה', null, 1 union all
select 392, 'אד"ם הכהן', null, 1 union all
select 393, 'ליברמן', null, 1 union all
select 394, 'ויזל', null, 1 union all
select 395, 'יהל"ל', null, 1 union all
select 396, 'שד בן גוריון', 'בן גוריון', 1 union all
select 397, 'לסל', null, 1 union all
select 398, 'אהרון דוד גורדון', null, 1 union all
select 399, 'ברנשטיין אדוארד', null, 1 union all
select 400, 'רנ"ק', 'רנק', 1 union all
select 401, 'וייס אייזיק הירש', null, 1 union all
select 402, 'וייס רפאל', null, 1 union all
select 403, 'גרץ', null, 1 union all
select 404, 'שיר', 'שי"ר', 1 union all
select 405, 'רחל', null, 1 union all
select 406, 'מלון אורה', null, 1 union all
select 407, 'סמ בן יהודה', null, 1 union all
select 408, 'מלון בזל', null, 1 union all
select 409, 'אמיל זולה', null, 1 union all
select 410, 'ז''ורס ז''אן', 'זאן זורס,זאן ז''ורס,זורס זאן', 1 union all
select 411, 'ביירון', null, 1 union all
select 412, 'קורולנקו', null, 1 union all
select 413, 'נתן החכם', null, 1 union all
select 414, 'הוז דב', 'הוז דוב', 1 union all
select 415, 'ישורון', null, 1 union all
select 416, 'רופין', null, 1 union all
select 417, 'ארנון', null, 1 union all
select 418, 'הכרם', null, 1 union all
select 419, 'עם ישראל חי', null, 1 union all
select 420, 'יהואש', null, 1 union all
select 421, 'של"ג', null, 1 union all
select 422, 'מאפו', null, 1 union all
select 423, 'מנדלי מוכר ספרים', 'מנדלי', 1 union all
select 424, 'בוגרשוב', null, 1 union all
select 425, 'טייגר היל', null, 1 union all
select 426, 'סירקין', null, 1 union all
select 427, 'סמולנסקין', null, 1 union all
select 428, 'פרוג', null, 1 union all
select 429, 'שלום עליכם', null, 1 union all
select 430, 'חובבי ציון', null, 1 union all
select 431, 'בן עמי', null, 1 union all
select 432, 'גנסין', null, 1 union all
select 433, 'פינסקר', null, 1 union all
select 434, 'בילינסון', null, 1 union all
select 435, 'אהרונוביץ', null, 1 union all
select 436, 'דרויאנוב', null, 1 union all
select 437, 'לוריא', null, 1 union all
select 438, 'גליקסון', null, 1 union all
select 439, 'צפת', null, 1 union all
select 440, 'טבריה', null, 1 union all
select 441, 'רציף הירקון', null, 1 union all
select 442, 'פרי אליעזר', null, 1 union all
select 443, 'דיזנגוף סנטר', null, 1 union all
select 444, 'קהילת קליבלנד', null, 1 union all
select 445, 'חוף גורדון', null, 1 union all
select 446, 'מלון קרלטון', null, 1 union all
select 447, 'מרינה', null, 1 union all
select 448, 'פרופ'' יובל נאמן', null, 1 union all
select 449, 'מנדלסון', null, 1 union all
select 450, 'שפינוזה', null, 1 union all
select 451, 'פילון', null, 1 union all
select 452, 'כהן הרמן', 'הרמן כהן', 1 union all
select 453, 'ריינס', null, 1 union all
select 454, 'גוטליב', null, 1 union all
select 455, 'הירשנברג', 'הירשינברג', 1 union all
select 456, 'ש"ץ', 'שץ', 1 union all
select 457, 'ישראליס', null, 1 union all
select 458, 'שלמה המלך', null, 1 union all
select 459, 'גורדון י ל', null, 1 union all
select 460, 'סמ יל"ג', null, 1 union all
select 461, 'סמ גור אריה', null, 1 union all
select 462, 'פרישמן', null, 1 union all
select 463, 'לכיש', null, 1 union all
select 464, 'מלון אסטור', null, 1 union all
select 465, 'מגידו', null, 1 union all
select 466, 'מצפה', null, 1 union all
select 467, 'גזר', null, 1 union all
select 468, 'שטנד', null, 1 union all
select 469, 'רייך', null, 1 union all
select 470, 'שד מסריק', null, 1 union all
select 471, 'שדרות ח"ן', null, 1 union all
select 472, 'אימבר', null, 1 union all
select 473, 'נצח ישראל', null, 1 union all
select 474, 'גדעון', null, 1 union all
select 475, 'השופטים', null, 1 union all
select 476, 'לטריס', null, 1 union all
select 477, 'הנביאים', 'נביאים', 1 union all
select 478, 'מלכי ישראל', null, 1 union all
select 479, 'שמשון', null, 1 union all
select 480, 'ספיר', null, 1 union all
select 481, 'ספיר אליהו', null, 1 union all
select 482, 'סמ רשבג', null, 1 union all
select 483, 'המליץ', null, 1 union all
select 484, 'בוקי בן יגלי', null, 1 union all
select 485, 'המלך ג''ורג''', null, 1 union all
select 486, 'בר גיורא', null, 1 union all
select 487, 'עין חרוד', null, 1 union all
select 488, 'תל חי', null, 1 union all
select 489, 'זמנהוף', null, 1 union all
select 490, 'אסתר המלכה', null, 1 union all
select 491, 'שולמית', null, 1 union all
select 492, 'רות', null, 1 union all
select 493, 'יעל', null, 1 union all
select 494, 'שפירא צבי', null, 1 union all
select 495, 'שמריהו לוין', null, 1 union all
select 496, 'שד'' תרס"ט', null, 1 union all
select 497, 'חיסין', null, 1 union all
select 498, 'שד בן ציון', 'בן ציון', 1 union all
select 499, 'לב אברהם', null, 1 union all
select 500, 'מרמורק', null, 1 union all
select 501, 'ביל"ו', null, 1 union all
select 502, 'טוסקניני', null, 1 union all
select 503, 'הוברמן', null, 1 union all
select 504, 'יוסף אליהו', null, 1 union all
select 505, 'האלקושי', null, 1 union all
select 506, 'רוזנבאום', null, 1 union all
select 507, 'פולד ברכה', null, 1 union all
select 508, 'סטארה אלברט', null, 1 union all
select 509, 'צוויג סטפן', null, 1 union all
select 510, 'פינלס', null, 1 union all
select 511, 'בובליק', null, 1 union all
select 512, 'שלומציון המלכה', null, 1 union all
select 513, 'בני דן', null, 1 union all
select 514, 'מתתיהו כהן גדול', null, 1 union all
select 515, 'יוחנן הגדי', null, 1 union all
select 516, 'יונתן הופסי', null, 1 union all
select 517, 'אונקלוס', null, 1 union all
select 518, 'לואי מרשל', null, 1 union all
select 519, 'דה האז', null, 1 union all
select 520, 'מרים החשמונאית', null, 1 union all
select 521, 'חוני המעגל', null, 1 union all
select 522, 'אנטיגונוס', null, 1 union all
select 523, 'יהודה המכבי', null, 1 union all
select 524, 'אלעזר החורני', null, 1 union all
select 525, 'אריסטובול', null, 1 union all
select 526, 'שטריקר', null, 1 union all
select 527, 'שד סמאטס', null, 1 union all
select 528, 'ברנדיס', null, 1 union all
select 529, 'הרב צירלסון', null, 1 union all
select 530, 'ועידת קטוביץ', null, 1 union all
select 531, 'הרב פרידמן', null, 1 union all
select 532, 'רילף יצחק', null, 1 union all
select 533, 'רב צעיר', null, 1 union all
select 534, 'שלזינגר', null, 1 union all
select 535, 'הילדסהיימר', null, 1 union all
select 536, 'ניסנבוים', null, 1 union all
select 537, 'הרב עמיאל', null, 1 union all
select 538, 'ויצמן', null, 1 union all
select 539, 'בני משה', null, 1 union all
select 540, 'בירנבוים', null, 1 union all
select 541, 'ירושלמי', null, 1 union all
select 542, 'תוספתא', null, 1 union all
select 543, 'הכנסת הגדולה', null, 1 union all
select 544, 'בבלי', null, 1 union all
select 545, 'בן סירא', null, 1 union all
select 546, 'זמר חנה', null, 1 union all
select 547, 'מרגלית מאיר', null, 1 union all
select 548, 'הזוהר', null, 1 union all
select 549, 'המשנה', null, 1 union all
select 550, 'הנשיאים', null, 1 union all
select 551, 'פעמוני יוסף', null, 1 union all
select 552, 'סנהדרין', null, 1 union all
select 553, 'רחבת מילאנו', null, 1 union all
select 554, 'הרב ניסים', null, 1 union all
select 555, 'זטורי משה', null, 1 union all
select 556, 'שטינמן', null, 1 union all
select 557, 'עקיבא אריה', null, 1 union all
select 558, 'אהבת ציון', null, 1 union all
select 559, 'חיותמן', null, 1 union all
select 560, 'דנין', null, 1 union all
select 561, 'סמילנסקי', null, 1 union all
select 562, 'שרת משה', null, 1 union all
select 563, 'גור יהודה', null, 1 union all
select 564, 'שד הציונות', null, 1 union all
select 565, 'ויסוצקי', null, 1 union all
select 566, 'בילטמור', null, 1 union all
select 567, 'חנקין', null, 1 union all
select 568, 'קרמניצקי', null, 1 union all
select 569, 'פנקס', null, 1 union all
select 570, 'בודנהיימר', null, 1 union all
select 571, 'הא באייר', null, 1 union all
select 572, 'שור', null, 1 union all
select 573, 'מוזיר יעקב', null, 1 union all
select 574, 'ילין דוד', null, 1 union all
select 575, 'אפשטיין', null, 1 union all
select 576, 'מוסינזון', null, 1 union all
select 577, 'אבן ג''נאח', null, 1 union all
select 578, 'רד"ק', null, 1 union all
select 579, 'בן סרוק', null, 1 union all
select 580, 'בן שפרוט', null, 1 union all
select 581, 'בן לברט', null, 1 union all
select 582, 'רח 4811', null, 1 union all
select 583, 'רמז דוד', null, 1 union all
select 584, 'מטמון כהן', null, 1 union all
select 585, 'חדרה', null, 1 union all
select 586, 'תש"ח', null, 1 union all
select 587, 'הלסינקי', null, 1 union all
select 588, 'ליסין', null, 1 union all
select 589, 'ארלוזורוב', 'ארלוזרוב', 1 union all
select 590, 'פייבל', null, 1 union all
select 591, 'זלוציסטי', null, 1 union all
select 592, 'קליי', null, 1 union all
select 593, 'זכרון יעקב', null, 1 union all
select 594, 'חברה חדשה', null, 1 union all
select 595, 'בלקינד', null, 1 union all
select 596, 'גלוסקין', null, 1 union all
select 597, 'כהנשטם', null, 1 union all
select 598, 'השופט נופך', null, 1 union all
select 599, 'גבעת המורה', null, 1 union all
select 600, 'ליפסקי לואי', null, 1 union all
select 601, 'רח 9721', null, 1 union all
select 602, 'מסוף רדינג', null, 1 union all
select 603, 'מסוף ארלוזורוב', null, 1 union all
select 604, 'דוש', null, 1 union all
select 605, 'בוסקוביץ', null, 1 union all
select 606, 'אלוני ניסים', null, 1 union all
select 607, 'רח 7921', null, 1 union all
select 608, 'רח 6921', null, 1 union all
select 609, 'הרב גורן שלמה', null, 1 union all
select 610, 'על פרשת דרכים', null, 1 union all
select 611, 'רח 4821', null, 1 union all
select 612, 'בארי', null, 1 union all
select 613, 'סולד הנרייטה', null, 1 union all
select 614, 'התמר', null, 1 union all
select 615, 'דרך נמיר מרדכי', null, 1 union all
select 616, 'הרימון', null, 1 union all
select 617, 'הגפן', null, 1 union all
select 618, 'הזית', null, 1 union all
select 619, 'התאנה', null, 1 union all
select 620, 'דפנה', null, 1 union all
select 621, 'שילה', null, 1 union all
select 622, 'מודיליאני', null, 1 union all
select 623, 'גליצנשטין', null, 1 union all
select 624, 'בצלאל', null, 1 union all
select 625, 'סוטין', null, 1 union all
select 626, 'אורי', null, 1 union all
select 627, 'פישמן מימון', null, 1 union all
select 628, 'נהרדעא', null, 1 union all
select 629, 'פומבדיתא', null, 1 union all
select 630, 'בלוך דוד', null, 1 union all
select 631, 'רב אלוף יעקב דורי', null, 1 union all
select 632, 'חכמי קירואן', null, 1 union all
select 633, 'רמברנדט', null, 1 union all
select 634, 'שטרוק', null, 1 union all
select 635, 'ליליאן', null, 1 union all
select 636, 'אנטוקולסקי', null, 1 union all
select 637, 'צייטלין', null, 1 union all
select 638, 'דובנוב', null, 1 union all
select 639, 'שד דוד המלך', null, 1 union all
select 640, 'בריינין ראובן', null, 1 union all
select 641, 'שד שאול המלך', null, 1 union all
select 642, 'דוליצקי', null, 1 union all
select 643, 'קצנלסון יצחק', null, 1 union all
select 644, 'אבן גבירול', null, 1 union all
select 645, 'מאנה', null, 1 union all
select 646, 'דה וינצ''י לאונרדו', null, 1 union all
select 647, 'זיו רבקה', null, 1 union all
select 648, 'מעלה שמיר משה', null, 1 union all
select 649, 'ברקוביץ', null, 1 union all
select 650, 'מרכז גולדה מאיר', null, 1 union all
select 651, 'ספיר פנחס', null, 1 union all
select 652, 'יהודה הלוי', null, 1 union all
select 653, 'ברדיצ''בסקי', null, 1 union all
select 654, 'שד רוטשילד', null, 1 union all
select 655, 'אחד העם', null, 1 union all
select 656, 'כרמיה', null, 1 union all
select 657, 'החשמונאים', null, 1 union all
select 658, 'לונץ', null, 1 union all
select 659, 'בר אילן', null, 1 union all
select 660, 'שיינקין', null, 1 union all
select 661, 'הגלבוע', null, 1 union all
select 662, 'מרכז בעלי מלאכה', null, 1 union all
select 663, 'נפחא יצחק', null, 1 union all
select 664, 'העבודה', null, 1 union all
select 665, 'חיות פרץ', null, 1 union all
select 666, 'רש"י', null, 1 union all
select 667, 'לאן א', null, 1 union all
select 668, 'סמטה אלמונית', null, 1 union all
select 669, 'סמטה פלונית', null, 1 union all
select 670, 'מיכ"ל', null, 1 union all
select 671, 'בורוכוב', null, 1 union all
select 672, 'חיים ואלישע', null, 1 union all
select 673, 'ורבורג', null, 1 union all
select 674, 'שבע השקמים', null, 1 union all
select 675, 'משעול יעקב', null, 1 union all
select 676, 'רבנו תם', null, 1 union all
select 677, 'טרומפלדור', null, 1 union all
select 678, 'ברוק צבי', 'ברוק ', 1 union all
select 679, 'ברנשטין כהן', null, 1 union all
select 680, 'שניאור זלמן', null, 1 union all
select 681, 'בר כוכבא', null, 1 union all
select 682, 'שמעון בר כוכבא', null, 1 union all
select 683, 'המכבי', null, 1 union all
select 684, 'בית לחם', null, 1 union all
select 685, 'אלנבי', null, 1 union all
select 686, 'אלו מציאות', null, 1 union all
select 687, 'ביאליק', null, 1 union all
select 688, 'אידלסון אברהם', null, 1 union all
select 689, 'הס משה', 'הס', 1 union all
select 690, 'טשרניחובסקי', null, 1 union all
select 691, 'חברון', null, 1 union all
select 692, 'בית החיים', null, 1 union all
select 693, 'רציף הרברט סמואל', null, 1 union all
select 694, 'נס ציונה', null, 1 union all
select 695, 'סמ נס ציונה', null, 1 union all
select 696, 'הירדן', null, 1 union all
select 697, 'לאן ב', null, 1 union all
select 698, 'סמ גן מאיר', null, 1 union all
select 699, 'מורד הטיילת', null, 1 union all
select 700, 'מלון ימית', null, 1 union all
select 701, 'יונה הנביא', null, 1 union all
select 702, 'הכובשים', null, 1 union all
select 703, 'גאולה', null, 1 union all
select 704, 'הרב קוק', null, 1 union all
select 705, 'האר"י', null, 1 union all
select 706, 'אהרונסון', null, 1 union all
select 707, 'זרובבל', null, 1 union all
select 708, 'עזרא הסופר', null, 1 union all
select 709, 'דניאל', null, 1 union all
select 710, 'נחמיה', null, 1 union all
select 711, 'תרמ"ב', null, 1 union all
select 712, 'יום טוב', null, 1 union all
select 713, 'קפאח יחיה', null, 1 union all
select 714, 'סמ הכרמל', null, 1 union all
select 715, 'נחליאל', null, 1 union all
select 716, 'כנפי נשרים', null, 1 union all
select 717, 'קהילת עדן', null, 1 union all
select 718, 'ישכון', null, 1 union all
select 719, 'מל"ן', null, 1 union all
select 720, 'הכרמל', null, 1 union all
select 721, 'רבי מאיר', null, 1 union all
select 722, 'אלישיב', null, 1 union all
select 723, 'בית יוסף', null, 1 union all
select 724, 'אלשיך', null, 1 union all
select 725, 'רבן גמליאל', null, 1 union all
select 726, 'רבי עקיבא', null, 1 union all
select 727, 'גדרה', null, 1 union all
select 728, 'נג''ארה ישראל', null, 1 union all
select 729, 'הלל הזקן', null, 1 union all
select 730, 'השומר', null, 1 union all
select 731, 'נחלת בנימין', null, 1 union all
select 732, 'רמב"ם', null, 1 union all
select 733, 'סמ שפ"ר', null, 1 union all
select 734, 'התבור', null, 1 union all
select 735, 'רבינוביץ שפ"ר', null, 1 union all
select 736, 'צדוק הכהן', null, 1 union all
select 737, 'קלישר', null, 1 union all
select 738, 'יעב"ץ', null, 1 union all
select 739, 'סמ התבור', null, 1 union all
select 740, 'מוהליבר', null, 1 union all
select 741, 'גרוזנברג', null, 1 union all
select 742, 'ברנר', null, 1 union all
select 743, 'שטראוס', null, 1 union all
select 744, 'פיארברג', null, 1 union all
select 745, 'מלצ''ט', null, 1 union all
select 746, 'יבנה', null, 1 union all
select 747, 'עין ורד', null, 1 union all
select 748, 'יוסף הנשיא', null, 1 union all
select 749, 'יוחנן הסנדלר', null, 1 union all
select 750, 'אליוט ג''ורג''', null, 1 union all
select 751, 'מונטיפיורי', null, 1 union all
select 752, 'נטר קרל', null, 1 union all
select 753, 'יוחנן בן זכאי', null, 1 union all
select 754, 'בית השואבה', null, 1 union all
select 755, 'השחר', null, 1 union all
select 756, 'הר סיני', null, 1 union all
select 757, 'אחוזת בית', null, 1 union all
select 758, 'אנגל', null, 1 union all
select 759, 'המגיד', null, 1 union all
select 760, 'בלפור', null, 1 union all
select 761, 'מזא"ה', null, 1 union all
select 762, 'נחמני', null, 1 union all
select 763, 'יפה בצלאל', null, 1 union all
select 764, 'סמ האור', null, 1 union all
select 765, 'הרכבת', null, 1 union all
select 766, 'גת רימון', null, 1 union all
select 767, 'דה פיג''וטו', null, 1 union all
select 768, 'שד"ל', null, 1 union all
select 769, 'רמח"ל', null, 1 union all
select 770, 'החשמל', null, 1 union all
select 771, 'ברזילי', null, 1 union all
select 772, 'לבונטין', null, 1 union all
select 773, 'מקוה ישראל', null, 1 union all
select 774, 'סמ הגינה', null, 1 union all
select 775, 'לשם', null, 1 union all
select 776, 'חבשוש חיים', null, 1 union all
select 777, 'דרך יפו', null, 1 union all
select 778, 'סמ בית הבד', null, 1 union all
select 779, 'רוקח שמעון', null, 1 union all
select 780, 'שטיין', null, 1 union all
select 781, 'שרעבי', null, 1 union all
select 782, 'כפר סבא', null, 1 union all
select 783, 'בוסתנאי', null, 1 union all
select 784, 'לילינבלום', null, 1 union all
select 785, 'מולכו שלמה', null, 1 union all
select 786, '3952', null, 1 union all
select 787, 'תחכמוני', null, 1 union all
select 788, 'סמ תחכמוני', null, 1 union all
select 789, 'עין גנים', null, 1 union all
select 790, 'היכל התלמוד', null, 1 union all
select 791, 'סמ מולכו', null, 1 union all
select 792, 'נוה צדק', null, 1 union all
select 793, 'סמ נוה צדק', null, 1 union all
select 794, 'אלחנן יצחק', null, 1 union all
select 795, 'עצמון', null, 1 union all
select 796, 'לפין', null, 1 union all
select 797, 'יבנאל', null, 1 union all
select 798, 'מחנה יוסף', null, 1 union all
select 799, 'דגניה', null, 1 union all
select 800, 'החרמון', null, 1 union all
select 801, 'התלמי יהושע', null, 1 union all
select 802, 'שבזי', null, 1 union all
select 803, 'יהודה החסיד', null, 1 union all
select 804, 'סמ שבזי', null, 1 union all
select 805, 'כנרת', null, 1 union all
select 806, 'פינס', null, 1 union all
select 807, 'סמ החרמון', null, 1 union all
select 808, 'מטולה', null, 1 union all
select 809, 'עין יעקב', null, 1 union all
select 810, 'אחווה', null, 1 union all
select 811, 'שלוש', null, 1 union all
select 812, 'מגדל', null, 1 union all
select 813, 'סמ מגדל', null, 1 union all
select 814, 'חברת ש"ס', null, 1 union all
select 815, 'השנית', null, 1 union all
select 816, 'יקינתון', null, 1 union all
select 817, 'המרד', null, 1 union all
select 818, 'איל"ן', null, 1 union all
select 819, '1330', null, 1 union all
select 820, 'שלהבית', null, 1 union all
select 821, 'גוש 6007', null, 1 union all
select 822, 'לוע הארי', null, 1 union all
select 823, 'תרצ"ו', null, 1 union all
select 824, 'אילת', null, 1 union all
select 825, 'סמ שלוש', null, 1 union all
select 826, 'אשקלון', null, 1 union all
select 827, 'רח 3357', null, 1 union all
select 828, 'אולשן יצחק', null, 1 union all
select 829, 'ברנט', null, 1 union all
select 830, 'שמרלינג', null, 1 union all
select 831, 'אבא ושרה נאמן', null, 1 union all
select 832, 'כל ישראל חברים', null, 1 union all
select 833, 'אמזלג', null, 1 union all
select 834, 'יחיאלי', null, 1 union all
select 835, 'באר יעקב', null, 1 union all
select 836, 'נוה שלום', null, 1 union all
select 837, 'אלרואי', null, 1 union all
select 838, 'בית הנוער', null, 1 union all
select 839, 'גוש 8007', null, 1 union all
select 840, 'מישאל', null, 1 union all
select 841, 'חנניה', null, 1 union all
select 842, 'כרמלית', null, 1 union all
select 843, 'תרפט', null, 1 union all
select 844, 'גוש 5007', null, 1 union all
select 845, 'המצודה', null, 1 union all
select 846, 'עזריה', null, 1 union all
select 847, 'צורית', null, 1 union all
select 848, 'גוטמאכר', null, 1 union all
select 849, 'חוסן', null, 1 union all
select 850, 'הרב עוזיאל', null, 1 union all
select 851, 'ישיבת וולוז''ין', null, 1 union all
select 852, 'אלעזר (רוקח)', null, 1 union all
select 853, 'גומא', null, 1 union all
select 854, 'גלזנר', null, 1 union all
select 855, 'חזון איש', null, 1 union all
select 856, 'ברגנר אליזבת', null, 1 union all
select 857, 'מאה שערים', null, 1 union all
select 858, 'חלץ', null, 1 union all
select 859, 'גוש 4007', null, 1 union all
select 860, 'ראשונים', null, 1 union all
select 861, 'שביל האטד', null, 1 union all
select 862, 'הרב טולידנו', null, 1 union all
select 863, 'קוסובסקי', null, 1 union all
select 864, 'הרב הרצוג', null, 1 union all
select 865, 'קויפמן יחזקאל', null, 1 union all
select 866, 'לוי יוסף', null, 1 union all
select 867, 'שנקר אריה', null, 1 union all
select 868, 'גולדמן נחום', null, 1 union all
select 869, 'מוזס ולטר', null, 1 union all
select 870, 'גולדברג', null, 1 union all
select 871, 'טיומקין', null, 1 union all
select 872, 'סעדיה גאון', null, 1 union all
select 873, 'לויד ג''ורג''', null, 1 union all
select 874, 'וילסון', null, 1 union all
select 875, 'לינקולן', null, 1 union all
select 876, 'כורש', null, 1 union all
select 877, 'אוליפנט', null, 1 union all
select 878, 'קרית ספר', null, 1 union all
select 879, 'עמרם גאון', null, 1 union all
select 880, 'קרליבך', null, 1 union all
select 881, 'חכמי דוד', null, 1 union all
select 882, 'ריב"ל', null, 1 union all
select 883, 'שונצינו', null, 1 union all
select 884, 'ראם', null, 1 union all
select 885, 'תושיה', null, 1 union all
select 886, 'חומה ומגדל', null, 1 union all
select 887, 'אלישברג', null, 1 union all
select 888, 'בית אלפא', null, 1 union all
select 889, 'בית עובד', null, 1 union all
select 890, 'בן אביגדור', null, 1 union all
select 891, 'האחים מסלאויטה', null, 1 union all
select 892, 'המלאכה', null, 1 union all
select 893, 'המקצוע', null, 1 union all
select 894, 'הצפירה', null, 1 union all
select 895, 'השפלה', null, 1 union all
select 896, 'התעשיה', null, 1 union all
select 897, 'יגיע כפיים', null, 1 union all
select 898, 'יד חרוצים', null, 1 union all
select 899, 'טברסקי', null, 1 union all
select 900, 'מיקוניס שמואל', null, 1 union all
select 901, 'רבניצקי', null, 1 union all
select 902, 'שאר ישוב', null, 1 union all
select 903, 'שבח', null, 1 union all
select 904, 'שטיבל', null, 1 union all
select 905, 'שפרינצק', null, 1 union all
select 906, 'לסקוב חיים', null, 1 union all
select 907, 'בן אב"י איתמר', null, 1 union all
select 908, 'קפלן', null, 1 union all
select 909, 'הארבעה', null, 1 union all
select 910, 'הפטמן', null, 1 union all
select 911, 'עין דור', null, 1 union all
select 912, 'פריש דניאל', null, 1 union all
select 913, 'שד יהודית', null, 1 union all
select 914, 'הנצי"ב', null, 1 union all
select 915, 'קארו יוסף', null, 1 union all
select 916, 'איסרליש', null, 1 union all
select 917, 'ילין מור נתן', null, 1 union all
select 918, 'בית הלל', null, 1 union all
select 919, 'שץ גגה גרשון', null, 1 union all
select 920, 'ב"ק ישראל', null, 1 union all
select 921, 'בית שמאי', null, 1 union all
select 922, 'המסגר', null, 1 union all
select 923, 'דרך בגין', null, 1 union all
select 924, 'דרך בגין מנחם', null, 1 union all
select 925, 'הרכב', null, 1 union all
select 926, 'שפע טל', null, 1 union all
select 927, 'ארניה אסוולדו', null, 1 union all
select 928, 'גבעון', null, 1 union all
select 929, 'צקלג', null, 1 union all
select 930, 'נחל איילון', null, 1 union all
select 931, 'אלוף מנדלר אברהם', null, 1 union all
select 932, 'אלוף מגן קלמן', null, 1 union all
select 933, 'רב אלוף דוד אלעזר', null, 1 union all
select 934, 'רח 8901', null, 1 union all
select 935, 'סטרכילביץ צבי', null, 1 union all
select 936, 'רח ה', null, 1 union all
select 937, 'מקלף מרדכי', null, 1 union all
select 938, 'פועה', null, 1 union all
select 939, 'גבעת התחמושת', null, 1 union all
select 940, 'רח 1274', null, 1 union all
select 941, 'רח 1275', null, 1 union all
select 942, 'רח 1276', null, 1 union all
select 943, 'רח 1277', null, 1 union all
select 944, 'רח 1278', null, 1 union all
select 945, 'נתיבי איילון דרום', null, 1 union all
select 946, 'נתיבי איילון צפון', null, 1 union all
select 947, 'קור פאול', null, 1 union all
select 948, 'רח 1243', null, 1 union all
select 949, 'רח 1244', null, 1 union all
select 950, 'רח ז', null, 1 union all
select 951, 'אליפלט', null, 1 union all
select 952, 'מעון', null, 1 union all
select 953, 'הנגרים', null, 1 union all
select 954, 'חצרים', null, 1 union all
select 955, 'המחוגה', null, 1 union all
select 956, 'המשור', null, 1 union all
select 957, 'צריפין', null, 1 union all
select 958, 'קומפרט', null, 1 union all
select 959, 'אוארבך', null, 1 union all
select 960, 'בר הופמן', null, 1 union all
select 961, 'שלבים', null, 1 union all
select 962, 'וסרמן יעקב', null, 1 union all
select 963, 'פראנצויז', null, 1 union all
select 964, 'רח 294', null, 1 union all
select 965, 'רח 305', null, 1 union all
select 966, 'רוחמה', null, 1 union all
select 967, 'נחמה', null, 1 union all
select 968, 'ניצנה', null, 1 union all
select 969, 'סגולה', null, 1 union all
select 970, 'שד ירושלים', null, 1 union all
select 971, 'בת עמי', null, 1 union all
select 972, 'פוריה', null, 1 union all
select 973, 'תרצה', null, 1 union all
select 974, 'דיצה', null, 1 union all
select 975, 'אפ"ק', null, 1 union all
select 976, 'הרבי מבכרך', null, 1 union all
select 977, 'רח 6193', null, 1 union all
select 978, 'עציון גבר', null, 1 union all
select 979, 'רח 3312', null, 1 union all
select 980, 'רח 7193', null, 1 union all
select 981, 'רבנו חננאל', null, 1 union all
select 982, 'אבולעפיה', null, 1 union all
select 983, 'הש"ך', null, 1 union all
select 984, 'אלפסי', null, 1 union all
select 985, 'רח 3093', null, 1 union all
select 986, 'רח 5093', null, 1 union all
select 987, 'שארית ישראל', null, 1 union all
select 988, 'התקומה', null, 1 union all
select 989, 'התחיה', null, 1 union all
select 990, 'רח 375', null, 1 union all
select 991, 'היתד', null, 1 union all
select 992, 'רח 973', null, 1 union all
select 993, 'חזק', null, 1 union all
select 994, 'אומץ', null, 1 union all
select 995, 'שמעון הצדיק', null, 1 union all
select 996, 'שמעיה', null, 1 union all
select 997, 'אלעזר בן עזריה', null, 1 union all
select 998, 'שמעון בן זומא', null, 1 union all
select 999, 'שמעון בן עזאי', null, 1 union all
select 1000, 'בן גמליאל', null, 1 union all
select 1001, 'בני בתירא', null, 1 union all
select 1002, 'אליעזר בן הורקנוס', null, 1 union all
select 1003, 'חנינא בן תרדיון', null, 1 union all
select 1004, 'אלעזר בן צדוק', null, 1 union all
select 1005, 'רזיאל', null, 1 union all
select 1006, 'הדואר', null, 1 union all
select 1007, 'בן שטח שמעון', null, 1 union all
select 1008, 'רח 3321', null, 1 union all
select 1009, 'הגמנסיה העברית', null, 1 union all
select 1010, 'המלך חירם', null, 1 union all
select 1011, 'רח 543', null, 1 union all
select 1012, 'רח 8333', null, 1 union all
select 1013, 'רוסלאן', null, 1 union all
select 1014, 'רטוש יונתן', null, 1 union all
select 1015, 'רח 282', null, 1 union all
select 1016, 'רח 8823', null, 1 union all
select 1017, 'פנחס בן יאיר', null, 1 union all
select 1018, 'בית אשל', null, 1 union all
select 1019, 'אבטליון', null, 1 union all
select 1020, 'אלעזר בן יוסי', null, 1 union all
select 1021, 'חנינא בן דוסא', null, 1 union all
select 1022, 'רח 3350', null, 1 union all
select 1023, 'יועזר איש הבירה', null, 1 union all
select 1024, 'שניצלר', null, 1 union all
select 1025, 'ליענר שלמה', null, 1 union all
select 1026, 'המנוע', null, 1 union all
select 1027, 'הפלך', null, 1 union all
select 1028, 'הכישור', null, 1 union all
select 1029, 'הזרם', null, 1 union all
select 1030, 'היסוד', null, 1 union all
select 1031, 'רח 7103', null, 1 union all
select 1032, 'רח 3018', null, 1 union all
select 1033, 'רח 3019', null, 1 union all
select 1034, 'רח 1203', null, 1 union all
select 1035, 'רח 3233', null, 1 union all
select 1036, 'רח 6333', null, 1 union all
select 1037, 'רח 1533', null, 1 union all
select 1038, 'רח 2673', null, 1 union all
select 1039, 'רח 9262', null, 1 union all
select 1040, 'רח 3361', null, 1 union all
select 1041, 'סגל צבי הרמן', null, 1 union all
select 1042, 'רח 382', null, 1 union all
select 1043, 'רח 1433', null, 1 union all
select 1044, 'סוגיהרה סמפו', null, 1 union all
select 1045, 'רח 0233', null, 1 union all
select 1046, 'סמטת הש"ך', null, 1 union all
select 1047, 'מרזוק ועזר', null, 1 union all
select 1048, 'רח 5393', null, 1 union all
select 1049, 'רח 4393', null, 1 union all
select 1050, 'רח 2393', null, 1 union all
select 1051, 'מפרץ שלמה', null, 1 union all
select 1052, 'הפנינים', null, 1 union all
select 1053, 'רח 7093', null, 1 union all
select 1054, 'רח 3028', null, 1 union all
select 1055, 'שמעון הבורסקי', null, 1 union all
select 1056, 'רח 1393', null, 1 union all
select 1057, 'העליה השניה', null, 1 union all
select 1058, 'שפתי ישנים', null, 1 union all
select 1059, 'רח 4293', null, 1 union all
select 1060, 'גוש 9107', null, 1 union all
select 1061, 'גוש 0407', null, 1 union all
select 1062, 'פסטר', null, 1 union all
select 1063, 'אבן סינא', null, 1 union all
select 1064, 'האגוז', null, 1 union all
select 1065, 'אחילוף', null, 1 union all
select 1066, 'שמואל בן עדיה', null, 1 union all
select 1067, 'אמונים', null, 1 union all
select 1068, 'אבן רשד', null, 1 union all
select 1069, 'הצרי', null, 1 union all
select 1070, 'בית רעים', null, 1 union all
select 1071, 'שריד', null, 1 union all
select 1072, 'הערמון', null, 1 union all
select 1073, 'רח 9293', null, 1 union all
select 1074, 'סייפן', null, 1 union all
select 1075, 'החרוב', null, 1 union all
select 1076, 'תות', null, 1 union all
select 1077, 'חייבי משה', null, 1 union all
select 1078, 'דודאים', null, 1 union all
select 1079, 'צנובר', null, 1 union all
select 1080, 'נסאר ג''ורג''', null, 1 union all
select 1081, 'רח 5293', null, 1 union all
select 1082, 'סלסלה', null, 1 union all
select 1083, 'בן אחיטוב', null, 1 union all
select 1084, 'תפוח', null, 1 union all
select 1085, 'דוד הראובני', null, 1 union all
select 1086, 'לונדון בצלאל', null, 1 union all
select 1087, 'רח 3094', null, 1 union all
select 1088, 'תמריר', null, 1 union all
select 1089, 'זהבי דוד', null, 1 union all
select 1090, 'רח 3083', null, 1 union all
select 1091, 'ההגה', null, 1 union all
select 1092, 'אלביטר עבדאלראוף', null, 1 union all
select 1093, 'רח 6293', null, 1 union all
select 1094, 'רח 1373', null, 1 union all
select 1095, 'רח 3733', null, 1 union all
select 1096, 'גרוסמן חייקה', null, 1 union all
select 1097, 'ויינר זאב', null, 1 union all
select 1098, 'התעודה האדומה', null, 1 union all
select 1099, 'רח 2373', null, 1 union all
select 1100, 'רח 0393', null, 1 union all
select 1101, 'רח 6303', null, 1 union all
select 1102, 'רח 0403', null, 1 union all
select 1103, 'הצדף', null, 1 union all
select 1104, 'השחף', null, 1 union all
select 1105, 'הדולפין', null, 1 union all
select 1106, 'העוגן', null, 1 union all
select 1107, 'רח 0473', null, 1 union all
select 1108, 'שערי ניקנור', null, 1 union all
select 1109, 'רח 8293', null, 1 union all
select 1110, 'נמל יפו', null, 1 union all
select 1111, 'המלחים', null, 1 union all
select 1112, 'קדם', null, 1 union all
select 1113, 'הספינה', null, 1 union all
select 1114, 'רב החובל', null, 1 union all
select 1115, 'התורן', null, 1 union all
select 1116, 'המשוט', null, 1 union all
select 1117, 'המפרש', null, 1 union all
select 1118, 'הקברניט', null, 1 union all
select 1119, 'רח 2473', null, 1 union all
select 1120, 'רח 2013', null, 1 union all
select 1121, 'רח 103', null, 1 union all
select 1122, 'רח 3750', null, 1 union all
select 1123, 'הדגה', null, 1 union all
select 1124, 'רח 7293', null, 1 union all
select 1125, 'צופית', null, 1 union all
select 1126, 'רח 101', null, 1 union all
select 1127, 'רח 153', null, 1 union all
select 1128, 'רח 157', null, 1 union all
select 1129, 'מכמורת', null, 1 union all
select 1130, 'הדייגים', null, 1 union all
select 1131, 'רח 131', null, 1 union all
select 1132, 'זיקים', null, 1 union all
select 1133, 'רח 251', null, 1 union all
select 1134, 'רח 561', null, 1 union all
select 1135, 'רח 551', null, 1 union all
select 1136, 'מכלל יופי', null, 1 union all
select 1137, 'מד אנדרומדה', null, 1 union all
select 1138, 'אזוב', null, 1 union all
select 1139, 'פייר מנדס פרנס', null, 1 union all
select 1140, 'שטרנהרץ', null, 1 union all
select 1141, 'המגיד מדובנא', null, 1 union all
select 1142, 'רח 3172', null, 1 union all
select 1143, 'דונולו הרופא', null, 1 union all
select 1144, 'שביב', null, 1 union all
select 1145, 'נבטים', null, 1 union all
select 1146, 'געש', null, 1 union all
select 1147, 'הסנה', null, 1 union all
select 1148, 'בצרה', null, 1 union all
select 1149, 'החטה', null, 1 union all
select 1150, 'הלוטוס', null, 1 union all
select 1151, 'השקמה', null, 1 union all
select 1152, 'הקיקיון', null, 1 union all
select 1153, 'עגור', null, 1 union all
select 1154, 'דישון', null, 1 union all
select 1155, 'ולנסיה', null, 1 union all
select 1156, 'מענית', null, 1 union all
select 1157, 'שלוחות', null, 1 union all
select 1158, 'הלענה', null, 1 union all
select 1159, 'רח 3144', null, 1 union all
select 1160, 'האשכולית', null, 1 union all
select 1161, 'עולש', null, 1 union all
select 1162, 'לוזים', null, 1 union all
select 1163, 'רח 3136', null, 1 union all
select 1164, 'רח 3142', null, 1 union all
select 1165, 'הלימון', null, 1 union all
select 1166, 'יסעור', null, 1 union all
select 1167, 'השעורה', null, 1 union all
select 1168, 'השיפון', null, 1 union all
select 1169, 'טולוז', null, 1 union all
select 1170, 'בית פלט', null, 1 union all
select 1171, 'האלומה', null, 1 union all
select 1172, 'רח 3178', null, 1 union all
select 1173, 'השיבולת', null, 1 union all
select 1174, 'רח 331', null, 1 union all
select 1175, 'ים סוף', null, 1 union all
select 1176, 'אסף הרופא', null, 1 union all
select 1177, 'מנוחה', null, 1 union all
select 1178, 'בת גלים', null, 1 union all
select 1179, 'המרפא', null, 1 union all
select 1180, 'הנופש', null, 1 union all
select 1181, 'קורצ''אק יאנוש', null, 1 union all
select 1182, 'שתי האחיות', null, 1 union all
select 1183, 'רח 1913', null, 1 union all
select 1184, 'האתרוג', null, 1 union all
select 1185, 'ההדס', null, 1 union all
select 1186, 'רח 6093', null, 1 union all
select 1187, 'רח 3175', null, 1 union all
select 1188, 'הערבה', null, 1 union all
select 1189, 'רח 6573', null, 1 union all
select 1190, 'רח 3180', null, 1 union all
select 1191, 'רח 3201', null, 1 union all
select 1192, 'רח 3179', null, 1 union all
select 1193, 'רח 7393', null, 1 union all
select 1194, 'רח 291', null, 1 union all
select 1195, 'קדרון', null, 1 union all
select 1196, 'מרגוע', null, 1 union all
select 1197, 'רח 3913', null, 1 union all
select 1198, 'רח 1613', null, 1 union all
select 1199, 'מנדלשטם אוסיפ', null, 1 union all
select 1200, 'בת ים', null, 1 union all
select 1201, 'רח 3195', null, 1 union all
select 1202, 'יטבת', null, 1 union all
select 1203, 'זכרון קדושים', null, 1 union all
select 1204, 'רח 002', null, 1 union all
select 1205, 'רח 3198', null, 1 union all
select 1206, 'שם הגדולים', null, 1 union all
select 1207, 'פחד יצחק', null, 1 union all
select 1208, 'רח 5573', null, 1 union all
select 1209, 'רח 3416', null, 1 union all
select 1210, 'רח 1303', null, 1 union all
select 1211, 'רח 701', null, 1 union all
select 1212, 'נתיב המזלות', null, 1 union all
select 1213, 'מזל בתולה', null, 1 union all
select 1214, 'מזל מאזנים', null, 1 union all
select 1215, 'מזל עקרב', null, 1 union all
select 1216, 'מזל קשת', null, 1 union all
select 1217, 'מזל סרטן', null, 1 union all
select 1218, 'מזל דגים', null, 1 union all
select 1219, 'מזל טלה', null, 1 union all
select 1220, 'מזל דלי', null, 1 union all
select 1221, 'מזל גדי', null, 1 union all
select 1222, 'מזל אריה', null, 1 union all
select 1223, 'מזל שור', null, 1 union all
select 1224, 'מזל תאומים', null, 1 union all
select 1225, 'המגדלור', null, 1 union all
select 1226, 'החלפנים', null, 1 union all
select 1227, 'רח 3887', null, 1 union all
select 1228, 'רח 6883', null, 1 union all
select 1229, 'רח 5883', null, 1 union all
select 1230, 'רח 1473', null, 1 union all
select 1231, 'רח 3888', null, 1 union all
select 1232, 'רח 4313', null, 1 union all
select 1233, 'רח 3889', null, 1 union all
select 1234, 'רח 4573', null, 1 union all
select 1235, 'רח 3890', null, 1 union all
select 1236, 'חריף אייזיק', null, 1 union all
select 1237, 'הצורפים', null, 1 union all
select 1238, 'שגב', null, 1 union all
select 1239, 'רח 1983', null, 1 union all
select 1240, 'רח 2983', null, 1 union all
select 1241, 'רח 4143', null, 1 union all
select 1242, 'רח 3413', null, 1 union all
select 1243, 'רח 2143', null, 1 union all
select 1244, 'אריסטו', null, 1 union all
select 1245, 'טימן יעקב', null, 1 union all
select 1246, 'רח 3408', null, 1 union all
select 1247, 'רח א סחנה ג', null, 1 union all
select 1248, 'רח 3383', null, 1 union all
select 1249, 'הגבול', null, 1 union all
select 1250, 'הולצברג שמחה', null, 1 union all
select 1251, 'רח ח סחנה ג', null, 1 union all
select 1252, 'אפלטון', null, 1 union all
select 1253, 'סוקרטס', null, 1 union all
select 1254, 'גוש 8407', null, 1 union all
select 1255, 'רח 3983', null, 1 union all
select 1256, 'רח 4983', null, 1 union all
select 1257, 'רח 4883', null, 1 union all
select 1258, 'רח 304', null, 1 union all
select 1259, 'רח 204', null, 1 union all
select 1260, 'רח 104', null, 1 union all
select 1261, 'רח 5043', null, 1 union all
select 1262, 'רח 3407', null, 1 union all
select 1263, 'רח יא סחנה ג', null, 1 union all
select 1264, 'רח יב סחנה ג', null, 1 union all
select 1265, 'רח ב סחנה ג', null, 1 union all
select 1266, 'רח ד סחנה ג', null, 1 union all
select 1267, 'עבודת ישראל', null, 1 union all
select 1268, 'מדרש פנחס', null, 1 union all
select 1269, 'מאור עינים', null, 1 union all
select 1270, 'שד חב"ד', null, 1 union all
select 1271, 'הרבי מפשיסחא', null, 1 union all
select 1272, 'רח 832', null, 1 union all
select 1273, 'שד הבאש"ט', null, 1 union all
select 1274, 'שד הבעש"ט', null, 1 union all
select 1275, 'דב ממזריץ', null, 1 union all
select 1276, 'אוהב ישראל', null, 1 union all
select 1277, 'ישראל מריז''ין', null, 1 union all
select 1278, 'נחמן מברסלב', null, 1 union all
select 1279, 'כ"ץ יעקב יוסף', null, 1 union all
select 1280, 'הסבא משפולה', null, 1 union all
select 1281, 'בת עין', null, 1 union all
select 1282, 'הרבי מלילוב', null, 1 union all
select 1283, 'הרבי מויטבסק', null, 1 union all
select 1284, 'הרבי מקוצק', null, 1 union all
select 1285, 'הרבי מקרלין', null, 1 union all
select 1286, 'חידושי הרי"ם', null, 1 union all
select 1287, 'ציהתל"י', null, 1 union all
select 1288, 'צהלון הרופא', null, 1 union all
select 1289, 'שמואל ירחינאי', null, 1 union all
select 1290, 'ישראלי יצחק', null, 1 union all
select 1291, 'טוביה הרופא', null, 1 union all
select 1292, 'דה פיליפ אדיס', null, 1 union all
select 1293, 'רח 211', null, 1 union all
select 1294, 'ליב בן שרה', null, 1 union all
select 1295, 'פנץ נתן', null, 1 union all
select 1296, 'רח'' 3214', null, 1 union all
select 1297, 'שויצר דוביד', null, 1 union all
select 1298, 'הרבי מקוטוב', null, 1 union all
select 1299, 'מעפילי סלואדור', null, 1 union all
select 1300, 'ארליך', null, 1 union all
select 1301, 'עבד אל גני', null, 1 union all
select 1302, 'עבד אל-גני', null, 1 union all
select 1303, 'רח'' 57', null, 1 union all
select 1304, 'תג''ר ציונה', null, 1 union all
select 1305, 'רח 3737', null, 1 union all
select 1306, 'פסטלוצי', null, 1 union all
select 1307, 'ולבה יואל', null, 1 union all
select 1308, 'רח 3738', null, 1 union all
select 1309, 'רח 3739', null, 1 union all
select 1310, 'מיכאל אנג''לו', null, 1 union all
select 1311, 'דאנטה', null, 1 union all
select 1312, 'ויקטור הוגו', null, 1 union all
select 1313, 'ראסין ז''אן', null, 1 union all
select 1314, 'פושקין', null, 1 union all
select 1315, 'גורקי', null, 1 union all
select 1316, 'אוז''שקובה', null, 1 union all
select 1317, 'רומן רולן', null, 1 union all
select 1318, 'עולי ציון', null, 1 union all
select 1319, 'נועם', null, 1 union all
select 1320, 'ריש גלותא', null, 1 union all
select 1321, 'בעלי התוספות', null, 1 union all
select 1322, 'שבטי ישראל', null, 1 union all
select 1323, 'רב האי גאון', null, 1 union all
select 1324, 'ארדון מרדכי', null, 1 union all
select 1325, 'רח 3048', null, 1 union all
select 1326, 'יהודה הימית', null, 1 union all
select 1327, 'רח 3335', null, 1 union all
select 1328, 'דרור', null, 1 union all
select 1329, 'בעל הטורים', null, 1 union all
select 1330, 'מגן אברהם', null, 1 union all
select 1331, 'אבן שושן אברהם', null, 1 union all
select 1332, 'דואר שושנה', null, 1 union all
select 1333, 'רח 3053', null, 1 union all
select 1334, 'יהודה מרגוזה', null, 1 union all
select 1335, 'יפת', null, 1 union all
select 1336, 'אביצור שמואל', null, 1 union all
select 1337, 'ספיר ברוך', null, 1 union all
select 1338, 'רבי חנינא', null, 1 union all
select 1339, 'הגיחון', null, 1 union all
select 1340, 'רבי פנחס', null, 1 union all
select 1341, 'עמיעד', null, 1 union all
select 1342, 'רבי נחמן', null, 1 union all
select 1343, 'רבי יוחנן', null, 1 union all
select 1344, 'רחבת אבוטבול יעקב', null, 1 union all
select 1345, 'יהושע בן פרחיה', null, 1 union all
select 1346, 'יוסי בן יוסי', null, 1 union all
select 1347, 'רבי אדא', null, 1 union all
select 1348, 'רבי תנחום', null, 1 union all
select 1349, 'רבי אחא', null, 1 union all
select 1350, 'קהילת אוסטרליה', null, 1 union all
select 1351, 'רח מו סחנה ג', null, 1 union all
select 1352, 'רח ג סחנה ג', null, 1 union all
select 1353, 'רח ה סחנה ג', null, 1 union all
select 1354, 'רח 1603', null, 1 union all
select 1355, 'מחנה אריאל', null, 1 union all
select 1356, 'מייזל זלמן', null, 1 union all
select 1357, 'רח 3055', null, 1 union all
select 1358, 'קיוסו אלברט', null, 1 union all
select 1359, 'סהרון', null, 1 union all
select 1360, 'פיקוס', null, 1 union all
select 1361, 'עירית', null, 1 union all
select 1362, 'הרב הלר חיים', null, 1 union all
select 1363, 'אבינרי יצחק', null, 1 union all
select 1364, '3933', null, 1 union all
select 1365, 'רובינשטיין יצחק', null, 1 union all
select 1366, 'רובינשטין', null, 1 union all
select 1367, 'רח 6043', null, 1 union all
select 1368, 'קרוא ברוך', null, 1 union all
select 1369, 'רח 3824', null, 1 union all
select 1370, 'רח 3404', null, 1 union all
select 1371, 'רח 0193', null, 1 union all
select 1372, 'רח 4193', null, 1 union all
select 1373, 'רח 5193', null, 1 union all
select 1374, 'רח 2193', null, 1 union all
select 1375, 'רח 3193', null, 1 union all
select 1376, 'באר שבע', null, 1 union all
select 1377, 'סמ באר שבע', null, 1 union all
select 1378, 'רח 324', null, 1 union all
select 1379, 'רח 222', null, 1 union all
select 1380, 'מדרש תנחומא', null, 1 union all
select 1381, 'נחל הבשור', null, 1 union all
select 1382, 'קדימה', null, 1 union all
select 1383, 'קוץ'' אדוארד', null, 1 union all
select 1384, 'רח 3241', null, 1 union all
select 1385, 'נחל עוז', null, 1 union all
select 1386, 'איסקוב נסים', null, 1 union all
select 1387, 'רח 3226', null, 1 union all
select 1388, 'גר צדק', null, 1 union all
select 1389, 'וכטנגוב', null, 1 union all
select 1390, 'חסידי האומות', null, 1 union all
select 1391, 'עזה', null, 1 union all
select 1392, 'מיצקביץ אדם', null, 1 union all
select 1393, 'אנדרוס', null, 1 union all
select 1394, 'רוזנבלט צבי', null, 1 union all
select 1395, 'רח 2996', null, 1 union all
select 1396, 'רח 381', null, 1 union all
select 1397, 'נס לגויים', null, 1 union all
select 1398, 'עדולם', null, 1 union all
select 1399, 'היינה', null, 1 union all
select 1400, 'חבר הלאומים', null, 1 union all
select 1401, 'שרירא גאון', null, 1 union all
select 1402, 'למרטין', null, 1 union all
select 1403, 'רח 3071', null, 1 union all
select 1404, 'הלוי משה', null, 1 union all
select 1405, 'רח 3070', null, 1 union all
select 1406, 'דברי חיים', null, 1 union all
select 1407, 'אור החיים', null, 1 union all
select 1408, 'רבנו ירוחם', null, 1 union all
select 1409, 'רח 742', null, 1 union all
select 1410, 'סמ שרירא', null, 1 union all
select 1411, 'אשדוד', null, 1 union all
select 1412, 'דרך יגאל ידין', null, 1 union all
select 1413, 'רח 3382', null, 1 union all
select 1414, 'רח 1493', null, 1 union all
select 1415, 'רח 6833', null, 1 union all
select 1416, 'תל גבורים', null, 1 union all
select 1417, 'בית עולים שמעון', null, 1 union all
select 1418, 'רח 3389', null, 1 union all
select 1419, 'רח 3387', null, 1 union all
select 1420, 'גוש 3996', null, 1 union all
select 1421, 'רח 152א', null, 1 union all
select 1422, 'רח 2933', null, 1 union all
select 1423, 'רח 3393', null, 1 union all
select 1424, 'נחל שורק', null, 1 union all
select 1425, 'הכוזרי', null, 1 union all
select 1426, 'הגבורים', null, 1 union all
select 1427, 'ארבר מנחם', null, 1 union all
select 1428, 'נוזהה', null, 1 union all
select 1429, 'רח 1343', null, 1 union all
select 1430, 'רח 3812', null, 1 union all
select 1431, 'פעמונית', null, 1 union all
select 1432, 'קהילת קנדה', null, 1 union all
select 1433, 'החלוצים', null, 1 union all
select 1434, 'זבולון', null, 1 union all
select 1435, 'השוק', null, 1 union all
select 1436, 'השוק סמ', null, 1 union all
select 1437, 'מרחביה', null, 1 union all
select 1438, 'המשביר', null, 1 union all
select 1439, 'מרכלת', null, 1 union all
select 1440, 'רענן', null, 1 union all
select 1441, 'מזרחי', null, 1 union all
select 1442, 'הקישון', null, 1 union all
select 1443, 'כפר גלעדי', null, 1 union all
select 1444, 'גבולות', null, 1 union all
select 1445, 'אברבנאל', null, 1 union all
select 1446, 'הרא"ש', null, 1 union all
select 1447, 'הרצל', null, 1 union all
select 1448, 'העליה', null, 1 union all
select 1449, 'סמ העליה', null, 1 union all
select 1450, 'פלורנטין', null, 1 union all
select 1451, 'גנני', null, 1 union all
select 1452, 'אוריאל אקוסטה', null, 1 union all
select 1453, 'מסילת וולפסון', null, 1 union all
select 1454, 'מסילת וולפסן', null, 1 union all
select 1455, 'שד ושינגטון', null, 1 union all
select 1456, 'ויטל חיים', null, 1 union all
select 1457, 'קורדובירו', null, 1 union all
select 1458, 'בנבנישתי', null, 1 union all
select 1459, 'בן עטר', null, 1 union all
select 1460, 'צ''לנוב', null, 1 union all
select 1461, 'פרץ י ל', null, 1 union all
select 1462, 'חזנוביץ', null, 1 union all
select 1463, 'מסילת העולים', null, 1 union all
select 1464, 'מולדת', null, 1 union all
select 1465, 'הרב פרנקל', null, 1 union all
select 1466, 'אלוף בצלות', null, 1 union all
select 1467, 'בני ברק', null, 1 union all
select 1468, 'הגר"א', null, 1 union all
select 1469, 'ארלנג''ר', null, 1 union all
select 1470, 'פין', null, 1 union all
select 1471, 'סלומון', null, 1 union all
select 1472, 'הנגב', null, 1 union all
select 1473, 'השרון', null, 1 union all
select 1474, 'הגליל', null, 1 union all
select 1475, 'השומרון', null, 1 union all
select 1476, 'ראש פינה', null, 1 union all
select 1477, 'החרש', null, 1 union all
select 1478, 'מירון', null, 1 union all
select 1479, 'עין הקורא', null, 1 union all
select 1480, 'איילת השחר', null, 1 union all
select 1481, 'איגר עקיבא', null, 1 union all
select 1482, 'יסוד המעלה', null, 1 union all
select 1483, 'ראשון לציון', null, 1 union all
select 1484, 'רח 2', null, 1 union all
select 1485, 'הגדוד העברי', null, 1 union all
select 1486, 'נוה שאנן', null, 1 union all
select 1487, 'וולפסון', null, 1 union all
select 1488, 'רח 3183', null, 1 union all
select 1489, 'שטרן', null, 1 union all
select 1490, 'שביל עכו', null, 1 union all
select 1491, 'רח 3362', null, 1 union all
select 1492, 'סג''רה', null, 1 union all
select 1493, 'אהלי יעקב', null, 1 union all
select 1494, 'בכורי ציון', null, 1 union all
select 1495, 'שוקן', null, 1 union all
select 1496, 'רח 6243', null, 1 union all
select 1497, 'תחנה מרכזית', null, 1 union all
select 1498, 'לודויפול', null, 1 union all
select 1499, 'גולומב', null, 1 union all
select 1500, 'רח א מכבי חדשה', null, 1 union all
select 1501, 'רח ב מכבי חדשה', null, 1 union all
select 1502, 'רח ג מכבי חדשה', null, 1 union all
select 1503, 'ישראל מסלנט', null, 1 union all
select 1504, 'לבנדה', null, 1 union all
select 1505, 'קנטור', null, 1 union all
select 1506, 'דרך קיבוץ גלויות', null, 1 union all
select 1507, 'כרם חמד', null, 1 union all
select 1508, 'שטינברג', null, 1 union all
select 1509, 'השילוח', null, 1 union all
select 1510, 'האסיף', null, 1 union all
select 1511, 'כוכבי יצחק', null, 1 union all
select 1512, 'פרי עץ חיים', null, 1 union all
select 1513, 'ענתבי', null, 1 union all
select 1514, 'סמ ענתבי', null, 1 union all
select 1515, 'צמח דוד', null, 1 union all
select 1516, 'רח 3677', null, 1 union all
select 1517, 'תחנה מרכזית החדשה', null, 1 union all
select 1518, 'עמיר', null, 1 union all
select 1519, 'שד השלכת', null, 1 union all
select 1520, 'מנשה בן ישראל', null, 1 union all
select 1521, 'שיבת ציון', null, 1 union all
select 1522, 'בית קציר', null, 1 union all
select 1523, 'הקונגרס', null, 1 union all
select 1524, 'מטלון', null, 1 union all
select 1525, 'לוינסקי', null, 1 union all
select 1526, 'בית גוברין', null, 1 union all
select 1527, 'יון מצולה', null, 1 union all
select 1528, 'הראב"ע', null, 1 union all
select 1529, 'חובות הלבבות', null, 1 union all
select 1530, 'סמ עובד', null, 1 union all
select 1531, 'בן אשר', null, 1 union all
select 1532, 'מלבי"ם', null, 1 union all
select 1533, 'חיוג יהודה', null, 1 union all
select 1534, 'ידעיה הפניני', null, 1 union all
select 1535, 'רויגו אברהם', null, 1 union all
select 1536, 'פלקירה', null, 1 union all
select 1537, 'לצרוס משה', null, 1 union all
select 1538, 'מקור חיים', null, 1 union all
select 1539, 'בעל העקידה', null, 1 union all
select 1540, 'רלב"ג', null, 1 union all
select 1541, 'יש"ר מקנדיא', null, 1 union all
select 1542, 'התיבונים', null, 1 union all
select 1543, 'גבעת בן יהודה', null, 1 union all
select 1544, 'טורי זהב', null, 1 union all
select 1545, 'קרשקש חסדאי', null, 1 union all
select 1546, 'אבודרהם', null, 1 union all
select 1547, 'שח"ל', null, 1 union all
select 1548, 'דה מודינה אריה', null, 1 union all
select 1549, 'ראב"ד', null, 1 union all
select 1550, 'סמ ראב"ד', null, 1 union all
select 1551, 'סמ רבי פוזילוב', null, 1 union all
select 1552, 'מורה נבוכים', null, 1 union all
select 1553, 'לסקר', null, 1 union all
select 1554, 'שיפר', null, 1 union all
select 1555, 'מסילת ישרים', null, 1 union all
select 1556, 'רבי מאיר בעל הנס', null, 1 union all
select 1557, 'מימון שלמה', null, 1 union all
select 1558, 'שד חכמי ישראל', null, 1 union all
select 1559, 'חכמי לובלין', null, 1 union all
select 1560, 'מהרש"א', null, 1 union all
select 1561, 'בית חדש', null, 1 union all
select 1562, 'חכמי אתונה', null, 1 union all
select 1563, 'מאור הגולה', null, 1 union all
select 1564, 'בלבן מאיר', null, 1 union all
select 1565, 'שד הר ציון', null, 1 union all
select 1566, 'סמ הר ציון', null, 1 union all
select 1567, 'בר יוחאי', null, 1 union all
select 1568, 'סמ בר יוחאי', null, 1 union all
select 1569, 'העמל', null, 1 union all
select 1570, 'המנור', null, 1 union all
select 1571, 'הסדנה', null, 1 union all
select 1572, 'דרך שלמה', null, 1 union all
select 1573, 'ראשית חכמה', null, 1 union all
select 1574, 'שערי תשובה', null, 1 union all
select 1575, 'אליקום', null, 1 union all
select 1576, 'סמ ראשית חכמה', null, 1 union all
select 1577, 'חזקיהו המלך', null, 1 union all
select 1578, 'גוש 2607', null, 1 union all
select 1579, 'גוש 9696', null, 1 union all
select 1580, 'גוש 3607', null, 1 union all
select 1581, 'רח 3377', null, 1 union all
select 1582, 'רח 8393', null, 1 union all
select 1583, 'רח 3833', null, 1 union all
select 1584, 'עמיקם', null, 1 union all
select 1585, 'אסירי ציון', null, 1 union all
select 1586, 'נס הרים', null, 1 union all
select 1587, 'הקנאים', null, 1 union all
select 1588, 'תרפ"א', null, 1 union all
select 1589, 'מבקיעים', null, 1 union all
select 1590, 'גבעת כ"ח', null, 1 union all
select 1591, 'ניל"י', null, 1 union all
select 1592, 'סמ חכמי ישראל', null, 1 union all
select 1593, 'שלושת החיצים', null, 1 union all
select 1594, 'המבצעים', null, 1 union all
select 1595, 'הקלעים', null, 1 union all
select 1596, 'השיירות', null, 1 union all
select 1597, 'המשלטים', null, 1 union all
select 1598, 'השופר', null, 1 union all
select 1599, 'החצוצרה', null, 1 union all
select 1600, 'הקשת', null, 1 union all
select 1601, 'המצפן', null, 1 union all
select 1602, 'המגן', null, 1 union all
select 1603, 'הלפיד', null, 1 union all
select 1604, 'דרך בן צבי', null, 1 union all
select 1605, 'רח 6483', null, 1 union all
select 1606, 'החרמש', null, 1 union all
select 1607, 'הדגל', null, 1 union all
select 1608, 'בורמה', null, 1 union all
select 1609, 'הקרן', null, 1 union all
select 1610, 'שד הותיקים', null, 1 union all
select 1611, 'די רוסי', null, 1 union all
select 1612, 'מאירבר', null, 1 union all
select 1613, 'הזמיר', null, 1 union all
select 1614, 'גוז''קוב', null, 1 union all
select 1615, 'העוגב', null, 1 union all
select 1616, 'גלאנץ לייב', null, 1 union all
select 1617, 'הכינור', null, 1 union all
select 1618, 'גורי ישראל', null, 1 union all
select 1619, 'אחרון יוסף', null, 1 union all
select 1620, 'מינקובסקי', null, 1 union all
select 1621, 'זולצר', null, 1 union all
select 1622, 'קפלנסקי', null, 1 union all
select 1623, 'בוסל', null, 1 union all
select 1624, 'רינגלבלום', null, 1 union all
select 1625, 'שילר', null, 1 union all
select 1626, 'לבנדובסקי', null, 1 union all
select 1627, 'אנסקי', null, 1 union all
select 1628, 'צונזר', null, 1 union all
select 1629, 'היהודי זיס', null, 1 union all
select 1630, 'זיגלבוים', null, 1 union all
select 1631, 'ורשבסקי', null, 1 union all
select 1632, 'גולדפאדן', null, 1 union all
select 1633, 'השרביט', null, 1 union all
select 1634, 'דיק', null, 1 union all
select 1635, 'דשבסקי', null, 1 union all
select 1636, 'לקרט', null, 1 union all
select 1637, 'דריפוס', null, 1 union all
select 1638, 'זייד אלכסנדר', null, 1 union all
select 1639, 'אז"ר', null, 1 union all
select 1640, 'אופטושו יוסף', null, 1 union all
select 1641, 'קמינסקה', null, 1 union all
select 1642, 'החזיון', null, 1 union all
select 1643, 'רח 3785', null, 1 union all
select 1644, 'הירשביין', null, 1 union all
select 1645, 'שפיר קליין', null, 1 union all
select 1646, 'רח 3873', null, 1 union all
select 1647, 'בית יצקר', null, 1 union all
select 1648, 'הפטיש', null, 1 union all
select 1649, 'התנופה', null, 1 union all
select 1650, 'המפעל', null, 1 union all
select 1651, 'שביל המרץ', null, 1 union all
select 1652, 'משגב עם', null, 1 union all
select 1653, 'חיל השריון', null, 1 union all
select 1654, 'גרינבוים', null, 1 union all
select 1655, 'ליוויק', null, 1 union all
select 1656, 'סמ אסירי ציון', null, 1 union all
select 1657, 'גיתית', null, 1 union all
select 1658, 'רח 3628', null, 1 union all
select 1659, 'רח 9263', null, 1 union all
select 1660, 'רח 4873', null, 1 union all
select 1661, 'עלית הנוער', null, 1 union all
select 1662, 'נהלל', null, 1 union all
select 1663, 'ערבי נחל', null, 1 union all
select 1664, 'זימן', null, 1 union all
select 1665, 'ברוריה', null, 1 union all
select 1666, 'עמק ברכה', null, 1 union all
select 1667, 'יקנעם', null, 1 union all
select 1668, 'מעבר יבוק', null, 1 union all
select 1669, 'נחלת יצחק', null, 1 union all
select 1670, 'פרי מגדים', null, 1 union all
select 1671, 'פרחי אביב', null, 1 union all
select 1672, 'חפץ חיים', null, 1 union all
select 1673, 'אבני זכרון', null, 1 union all
select 1674, 'בן שמן', null, 1 union all
select 1675, 'גינוסר', null, 1 union all
select 1676, 'שביל החלב', null, 1 union all
select 1677, 'חיי אדם', null, 1 union all
select 1678, 'טירת צבי', null, 1 union all
select 1679, 'ילקוט הרועים', null, 1 union all
select 1680, 'מנורת המאור', null, 1 union all
select 1681, 'גלוסקא זכריה', null, 1 union all
select 1682, 'תוצרת הארץ', null, 1 union all
select 1683, 'אלון יגאל', null, 1 union all
select 1684, 'הסוללים', null, 1 union all
select 1685, 'ינון', null, 1 union all
select 1686, 'תובל', null, 1 union all
select 1687, 'הרקפת', null, 1 union all
select 1688, 'הפרגים', null, 1 union all
select 1689, 'הצבר', null, 1 union all
select 1690, 'הכלנית', null, 1 union all
select 1691, 'פליטי הספר', null, 1 union all
select 1692, 'הניצנים', null, 1 union all
select 1693, 'דם המכבים', null, 1 union all
select 1694, 'דרך דיין משה', null, 1 union all
select 1695, 'זכריני', null, 1 union all
select 1696, 'הצלף', null, 1 union all
select 1697, 'ניר עם', null, 1 union all
select 1698, 'היסמין', null, 1 union all
select 1699, 'הצפורן', null, 1 union all
select 1700, 'החרצית', null, 1 union all
select 1701, 'הדמומית', null, 1 union all
select 1702, 'החצב', null, 1 union all
select 1703, 'האספרגוס', null, 1 union all
select 1704, 'דרך הגבורה', null, 1 union all
select 1705, 'יפרח', null, 1 union all
select 1706, 'יניב', null, 1 union all
select 1707, 'ביצרון', null, 1 union all
select 1708, 'בצרון', null, 1 union all
select 1709, 'שד ההשכלה', null, 1 union all
select 1710, 'בן זאב', null, 1 union all
select 1711, 'גינצבורג', null, 1 union all
select 1712, 'ארטר יצחק', null, 1 union all
select 1713, 'גוטלובר', null, 1 union all
select 1714, 'שולמן', null, 1 union all
select 1715, 'צויפל', null, 1 union all
select 1716, 'סלונימסקי', null, 1 union all
select 1717, 'רובין שלמה', null, 1 union all
select 1718, 'מנדלקרן', null, 1 union all
select 1719, 'בן יעקב', null, 1 union all
select 1720, 'טביוב', null, 1 union all
select 1721, 'עמינדב', null, 1 union all
select 1722, 'יצחק שדה', null, 1 union all
select 1723, 'עין זיתים', null, 1 union all
select 1724, 'פאת השולחן', null, 1 union all
select 1725, 'מיטב', null, 1 union all
select 1726, 'וולמן יהודה', null, 1 union all
select 1727, 'בוקסנבאום יוסף', null, 1 union all
select 1728, 'הנרקיס', null, 1 union all
select 1729, 'רח 1135', null, 1 union all
select 1730, 'בנימיני אהרון', null, 1 union all
select 1731, 'סוסליק אריה', null, 1 union all
select 1732, 'מוזס יהודה ונח', null, 1 union all
select 1733, 'גובר רבקה', null, 1 union all
select 1734, 'לילי מנחם', null, 1 union all
select 1735, 'האומנים', null, 1 union all
select 1736, 'רח 5031', null, 1 union all
select 1737, 'רח 6031', null, 1 union all
select 1738, 'דרך הטייסים', null, 1 union all
select 1739, 'עמישב', null, 1 union all
select 1740, 'גונן', null, 1 union all
select 1741, 'דרך השלום', null, 1 union all
select 1742, 'אשרמן יוסף', null, 1 union all
select 1743, 'החבצלת', null, 1 union all
select 1744, 'הצבי', null, 1 union all
select 1745, 'עודד', null, 1 union all
select 1746, 'רח סו כ שלם', null, 1 union all
select 1747, 'רח סה כ שלם', null, 1 union all
select 1748, 'רח ד כפר שלם', null, 1 union all
select 1749, 'יפתח', null, 1 union all
select 1750, 'מלילות', null, 1 union all
select 1751, 'מסלול', null, 1 union all
select 1752, 'תעוז', null, 1 union all
select 1753, 'פרזון', null, 1 union all
select 1754, 'דימונה', null, 1 union all
select 1755, 'תמנע', null, 1 union all
select 1756, 'הרודיון', null, 1 union all
select 1757, 'טור מלכא', null, 1 union all
select 1758, 'נשרי צבי', null, 1 union all
select 1759, 'נגבה', null, 1 union all
select 1760, 'עין גב', null, 1 union all
select 1761, 'בית אורן', null, 1 union all
select 1762, 'מונאש', null, 1 union all
select 1763, 'קיש', null, 1 union all
select 1764, 'עיינות', null, 1 union all
select 1765, 'שפירא ישראל', null, 1 union all
select 1766, 'ברגי בנימין', null, 1 union all
select 1767, 'סמ איתן', null, 1 union all
select 1768, 'אריאל', null, 1 union all
select 1769, 'גבעתי', null, 1 union all
select 1770, 'בן חיל', null, 1 union all
select 1771, 'אלוף', null, 1 union all
select 1772, 'בית קשת', null, 1 union all
select 1773, 'מקראי קדש', null, 1 union all
select 1774, 'יגור', null, 1 union all
select 1775, 'מצודת בית"ר', null, 1 union all
select 1776, 'וינגייט', null, 1 union all
select 1777, 'הפורצים', null, 1 union all
select 1778, 'שער הגיא', null, 1 union all
select 1779, 'שד יד לבנים', null, 1 union all
select 1780, 'לוחמי גליפולי', null, 1 union all
select 1781, 'הפלמ"ח', null, 1 union all
select 1782, 'בת ציון', null, 1 union all
select 1783, 'הגבור האלמוני', null, 1 union all
select 1784, 'עמק איילון', null, 1 union all
select 1785, 'לה גארדיה', null, 1 union all
select 1786, 'מרגולין', null, 1 union all
select 1787, 'אנילביץ מרדכי', null, 1 union all
select 1788, 'סטרומה', null, 1 union all
select 1789, 'מורדי הגטאות', null, 1 union all
select 1790, 'בית ירח', null, 1 union all
select 1791, 'סנש חנה', null, 1 union all
select 1792, 'רייק חביבה', null, 1 union all
select 1793, 'שד המעפילים', null, 1 union all
select 1794, 'החותרים', null, 1 union all
select 1795, 'דרך ההגנה', null, 1 union all
select 1796, 'גוש עציון', null, 1 union all
select 1797, 'יציאת אירופה', null, 1 union all
select 1798, 'רייס רפאל', null, 1 union all
select 1799, 'סירני חיים', null, 1 union all
select 1800, 'הפרטיזן היהודי', null, 1 union all
select 1801, 'אני מאמין', null, 1 union all
select 1802, 'שד החי"ל', null, 1 union all
select 1803, 'פטרסון', null, 1 union all
select 1804, 'ווג''ווד', null, 1 union all
select 1805, 'התשעים ושלוש', null, 1 union all
select 1806, 'חניתה', null, 1 union all
select 1807, 'חרוץ', null, 1 union all
select 1808, 'נירים', null, 1 union all
select 1809, 'פטריה', null, 1 union all
select 1810, 'קיסריה', null, 1 union all
select 1811, 'השלושה', null, 1 union all
select 1812, 'המאבק', null, 1 union all
select 1813, 'המערכה', null, 1 union all
select 1814, 'הגייסות', null, 1 union all
select 1815, 'הסיירים', null, 1 union all
select 1816, 'ברנפלד שמעון', null, 1 union all
select 1817, 'בובר שלמה', null, 1 union all
select 1818, 'באכר זאב', null, 1 union all
select 1819, 'הרב רייפמן', null, 1 union all
select 1820, 'הורודצקי', null, 1 union all
select 1821, 'הרכבי אברהם', null, 1 union all
select 1822, 'שטינשנידר', null, 1 union all
select 1823, 'פוזננסקי שמואל', null, 1 union all
select 1824, 'דוידקה', null, 1 union all
select 1825, 'טשרנא', null, 1 union all
select 1826, 'שביל מרדכי', null, 1 union all
select 1827, 'קלמר משה', null, 1 union all
select 1828, 'רח 4206', null, 1 union all
select 1829, 'משעול שירה', null, 1 union all
select 1830, 'סמטת נטע', null, 1 union all
select 1831, 'רח 7083', null, 1 union all
select 1832, 'רחבת מרטון ארנסט', null, 1 union all
select 1833, 'רח 0131', null, 1 union all
select 1834, 'עוזר', null, 1 union all
select 1835, 'נוריאל', null, 1 union all
select 1836, 'סימן טוב', null, 1 union all
select 1837, 'הודיה', null, 1 union all
select 1838, 'חפר', null, 1 union all
select 1839, 'זרח', null, 1 union all
select 1840, 'עבאס אברהם', null, 1 union all
select 1841, 'ברכיה', null, 1 union all
select 1842, 'ורדיאל', null, 1 union all
select 1843, 'דעואל', null, 1 union all
select 1844, 'דורון', null, 1 union all
select 1845, 'היימן', null, 1 union all
select 1846, 'גדליה', null, 1 union all
select 1847, 'האגמון', null, 1 union all
select 1848, 'בלשן', null, 1 union all
select 1849, 'הברוש', null, 1 union all
select 1850, 'האקליפטוס', null, 1 union all
select 1851, 'קהילת ניו יורק', null, 1 union all
select 1852, 'השיטה', null, 1 union all
select 1853, 'קהילת מכסיקו', null, 1 union all
select 1854, 'סמ מסילה א', null, 1 union all
select 1855, 'סמ מסילה ב', null, 1 union all
select 1856, 'יחיעם', null, 1 union all
select 1857, 'ותיק', null, 1 union all
select 1858, 'ורד', null, 1 union all
select 1859, 'רשף', null, 1 union all
select 1860, 'מושיע', null, 1 union all
select 1861, 'יזהר', null, 1 union all
select 1862, 'אחיעזר', null, 1 union all
select 1863, 'שלמון', null, 1 union all
select 1864, 'אצ"ל', null, 1 union all
select 1865, 'השכל', null, 1 union all
select 1866, 'הונא', null, 1 union all
select 1867, 'לפידות', null, 1 union all
select 1868, 'לבלוב', null, 1 union all
select 1869, 'ישרש', null, 1 union all
select 1870, 'אביטל', null, 1 union all
select 1871, 'וילון', null, 1 union all
select 1872, 'בן חסד', null, 1 union all
select 1873, 'שבתאי', null, 1 union all
select 1874, 'קלמן', null, 1 union all
select 1875, 'עברי', null, 1 union all
select 1876, 'אביאסף', null, 1 union all
select 1877, 'הרן', null, 1 union all
select 1878, 'בועז', null, 1 union all
select 1879, 'כצנלסון בת שבע', null, 1 union all
select 1880, 'נדב', null, 1 union all
select 1881, 'רזי', null, 1 union all
select 1882, 'נעמן', null, 1 union all
select 1883, 'זבד', null, 1 union all
select 1884, 'אבימלך', null, 1 union all
select 1885, 'ביתוס', null, 1 union all
select 1886, 'קרייתי', null, 1 union all
select 1887, 'רח 3031', null, 1 union all
select 1888, 'רשפים', null, 1 union all
select 1889, 'רח צ', null, 1 union all
select 1890, 'רח פז', null, 1 union all
select 1891, 'רח פה', null, 1 union all
select 1892, 'רח פג', null, 1 union all
select 1893, 'רח פד', null, 1 union all
select 1894, 'איתיאל', null, 1 union all
select 1895, 'רח פ', null, 1 union all
select 1896, 'אחימעץ', null, 1 union all
select 1897, 'אביתר', null, 1 union all
select 1898, 'דרך בר לב חיים', null, 1 union all
select 1899, 'דרך בר-לב חיים', null, 1 union all
select 1900, 'פלוגות', null, 1 union all
select 1901, 'סמ מעוז', null, 1 union all
select 1902, 'יונדב', null, 1 union all
select 1903, 'צלופחד', null, 1 union all
select 1904, 'תרדיון', null, 1 union all
select 1905, 'תשבי', null, 1 union all
select 1906, 'ששון', null, 1 union all
select 1907, 'שמחה', null, 1 union all
select 1908, 'רוני', null, 1 union all
select 1909, 'קמואל', null, 1 union all
select 1910, 'עזאי', null, 1 union all
select 1911, 'התקוה', null, 1 union all
select 1912, 'קדמיאל', null, 1 union all
select 1913, 'נתן', null, 1 union all
select 1914, 'רצון', null, 1 union all
select 1915, 'סמדר', null, 1 union all
select 1916, 'צפריר', null, 1 union all
select 1917, 'צורישדי', null, 1 union all
select 1918, 'פנואל', null, 1 union all
select 1919, 'פלטיאל', null, 1 union all
select 1920, 'מבשר', null, 1 union all
select 1921, 'חנוך', null, 1 union all
select 1922, 'כביר', null, 1 union all
select 1923, 'כרמי', null, 1 union all
select 1924, 'ליש', null, 1 union all
select 1925, 'יקותיאל', null, 1 union all
select 1926, 'טלמון', null, 1 union all
select 1927, 'יאיר', null, 1 union all
select 1928, 'למואל', null, 1 union all
select 1929, 'טרפון', null, 1 union all
select 1930, 'הרותם', null, 1 union all
select 1931, 'גואל', null, 1 union all
select 1932, 'תדהר דוד', null, 1 union all
select 1933, 'המכבש', null, 1 union all
select 1934, 'מבחר', null, 1 union all
select 1935, 'סמ כביר', null, 1 union all
select 1936, 'רח 7884', null, 1 union all
select 1937, 'רח מו כ שלם', null, 1 union all
select 1938, 'רח מא כ שלם', null, 1 union all
select 1939, 'רח מג כ שלם', null, 1 union all
select 1940, 'רח מב כ שלם', null, 1 union all
select 1941, 'רח מד כ שלם', null, 1 union all
select 1942, 'נתיבות', null, 1 union all
select 1943, 'רח סא שכ'' הארגזים', null, 1 union all
select 1944, 'רח סל שכ'' הארגזים', null, 1 union all
select 1945, 'שתולים', null, 1 union all
select 1946, 'מלקוש', null, 1 union all
select 1947, 'גבעולים', null, 1 union all
select 1948, 'שרשים', null, 1 union all
select 1949, 'תמוז', null, 1 union all
select 1950, 'חירותנו', null, 1 union all
select 1951, 'תשרי', null, 1 union all
select 1952, 'אלול', null, 1 union all
select 1953, 'אב', null, 1 union all
select 1954, 'סמ זרת', null, 1 union all
select 1955, 'סיוון', null, 1 union all
select 1956, 'כסלו', null, 1 union all
select 1957, 'שבט', null, 1 union all
select 1958, 'אדר', null, 1 union all
select 1959, 'אייר', null, 1 union all
select 1960, 'שבלים', null, 1 union all
select 1961, 'טבת', null, 1 union all
select 1962, 'אורים', null, 1 union all
select 1963, 'חשון', null, 1 union all
select 1964, 'גדיש', null, 1 union all
select 1965, 'יורה', null, 1 union all
select 1966, 'קמה', null, 1 union all
select 1967, 'פלג', null, 1 union all
select 1968, 'דגן', null, 1 union all
select 1969, 'ימין', null, 1 union all
select 1970, 'יורם', null, 1 union all
select 1971, 'זרעים', null, 1 union all
select 1972, 'רח 0873', null, 1 union all
select 1973, 'מצובה', null, 1 union all
select 1974, 'רח סל', null, 1 union all
select 1975, 'הרטוב', null, 1 union all
select 1976, 'גופר', null, 1 union all
select 1977, 'בדולח', null, 1 union all
select 1978, 'דוחן', null, 1 union all
select 1979, 'נטעים', null, 1 union all
select 1980, 'לח"י', null, 1 union all
select 1981, 'רח 4211', null, 1 union all
select 1982, 'רח'' 4211', null, 1 union all
select 1983, 'הרב טייב יצחק', null, 1 union all
select 1984, 'ליבנה אליעזר', null, 1 union all
select 1985, 'הרב גביזון חי', null, 1 union all
select 1986, 'אלוף דן לנר', null, 1 union all
select 1987, 'רח 1084', null, 1 union all
select 1988, 'רח 5801', null, 1 union all
select 1989, 'רח מ כ שלם', null, 1 union all
select 1990, 'רח נט כ שלם', null, 1 union all
select 1991, 'בר כוכבא משה בריל', null, 1 union all
select 1992, 'משה בריל בר-כוכבא', null, 1 union all
select 1993, 'רח מז כ שלם', null, 1 union all
select 1994, 'רח כז כ שלם', null, 1 union all
select 1995, 'רח מח כ שלם', null, 1 union all
select 1996, 'רח מט כ שלם', null, 1 union all
select 1997, 'שייקה דן', null, 1 union all
select 1998, 'רח נ כ שלם', null, 1 union all
select 1999, 'רח כ כ שלם', null, 1 union all
select 2000, 'רח כד כ שלם', null, 1 union all
select 2001, 'רח כה כ שלם', null, 1 union all
select 2002, 'רח לט כ שלם', null, 1 union all
select 2003, 'רח ז כפר שלם', null, 1 union all
select 2004, 'מדמון מנחם', null, 1 union all
select 2005, 'רח ה כפר שלם', null, 1 union all
select 2006, 'רח כט כ שלם', null, 1 union all
select 2007, 'רח יט כ שלם', null, 1 union all
select 2008, 'רח יח כ שלם', null, 1 union all
select 2009, 'רח כח כ שלם', null, 1 union all
select 2010, 'רח כו כ שלם', null, 1 union all
select 2011, 'רח ו כפר שלם', null, 1 union all
select 2012, 'רח עג כ שלם', null, 1 union all
select 2013, 'רח ב כפר שלם', null, 1 union all
select 2014, 'רח יב כ שלם', null, 1 union all
select 2015, 'רח יא כ שלם', null, 1 union all
select 2016, 'רח ח כ שלם', null, 1 union all
select 2017, 'רח ט כ שלם', null, 1 union all
select 2018, 'רח יג כ שלם', null, 1 union all
select 2019, 'רח יד כ שלם', null, 1 union all
select 2020, 'רח יז כ שלם', null, 1 union all
select 2021, 'רח סב כ שלם', null, 1 union all
select 2022, 'רח טו כפר שלם', null, 1 union all
select 2023, 'רח סג כ שלם', null, 1 union all
select 2024, 'רח טז כפר שלם', null, 1 union all
select 2025, 'רח סד כ שלם', null, 1 union all
select 2026, 'רח לא כפר שלם', null, 1 union all
select 2027, 'רח נז כ שלם', null, 1 union all
select 2028, 'רח נח כ שלם', null, 1 union all
select 2029, 'רח סא כ שלם', null, 1 union all
select 2030, 'רח לה כפר שלם', null, 1 union all
select 2031, 'רח לו כפר שלם', null, 1 union all
select 2032, 'רח לג כפר שלם', null, 1 union all
select 2033, 'רח לד כפר שלם', null, 1 union all
select 2034, 'רח ל כפר שלם', null, 1 union all
select 2035, 'רח כג כפר שלם', null, 1 union all
select 2036, 'רח נו כ שלם', null, 1 union all
select 2037, 'רח כא כפר שלם', null, 1 union all
select 2038, 'רח לח כפר שלם', null, 1 union all
select 2039, 'רח נא כ שלם', null, 1 union all
select 2040, 'רח 4848', null, 1 union all
select 2041, 'רח לז כפר שלם', null, 1 union all
select 2042, 'רח נב כ שלם', null, 1 union all
select 2043, 'רח נה כ שלם', null, 1 union all
select 2044, 'רח י כ שלם', null, 1 union all
select 2045, 'רח נד כ שלם', null, 1 union all
select 2046, 'אליעז רפאל', null, 1 union all
select 2047, 'מח"ל', null, 1 union all
select 2048, 'שד ששת הימים', null, 1 union all
select 2049, 'מעפילי אגוז', null, 1 union all
select 2050, 'סנפיר', null, 1 union all
select 2051, 'צוקרמן יצחק', null, 1 union all
select 2052, 'תקוע', null, 1 union all
select 2053, 'בושם', null, 1 union all
select 2054, 'מור', null, 1 union all
select 2055, 'צרעה', null, 1 union all
select 2056, 'מוצא', null, 1 union all
select 2057, 'בירנית', null, 1 union all
select 2058, 'רח 5704', null, 1 union all
select 2059, 'גולינקין מרדכי', null, 1 union all
select 2060, 'צלילי חנינא', null, 1 union all
select 2061, 'הרצפלד אברהם', null, 1 union all
select 2062, 'הרב אלנקווה', null, 1 union all
select 2063, 'רוטנשטרייך', null, 1 union all
select 2064, 'סרלין יוסף', null, 1 union all
select 2065, 'סלע יעקב', null, 1 union all
select 2066, 'רח רי"ז', null, 1 union all
select 2067, 'רח'' 4218', null, 1 union all
select 2068, 'גבירטיג מרדכי', null, 1 union all
select 2069, 'רח'' 4219', null, 1 union all
select 2070, 'קורין עזרא', null, 1 union all
select 2071, 'לובטקין צביה', null, 1 union all
select 2072, 'קהילת ברזיל', null, 1 union all
select 2073, 'רח 6124', null, 1 union all
select 2074, 'רח 4217', null, 1 union all
select 2075, 'מבוא וולקר יוסף', null, 1 union all
select 2076, 'רח 2224', null, 1 union all
select 2077, 'רח 3224', null, 1 union all
select 2078, 'רח 4224', null, 1 union all
select 2079, 'מרדור מוניה', null, 1 union all
select 2080, 'אבידן שמעון', null, 1 union all
select 2081, 'רח 5514', null, 1 union all
select 2082, 'רי"ז', null, 1 union all
select 2083, 'רח 7684', null, 1 union all
select 2084, 'רח 4890', null, 1 union all
select 2085, 'רח 1784', null, 1 union all
select 2086, 'רח 1984', null, 1 union all
select 2087, 'רח 2984', null, 1 union all
select 2088, 'רח 3984', null, 1 union all
select 2089, 'ויל קורט', null, 1 union all
select 2090, 'פרוץ לאו', null, 1 union all
select 2091, 'חלמית', null, 1 union all
select 2092, 'חיננית', null, 1 union all
select 2093, 'גלעינית', null, 1 union all
select 2094, 'מחרוזת', null, 1 union all
select 2095, 'נרדור', null, 1 union all
select 2096, 'סומקן', null, 1 union all
select 2097, 'שז"ר זלמן', null, 1 union all
select 2098, 'אירוס', null, 1 union all
select 2099, 'דקל', null, 1 union all
select 2100, 'שקד', null, 1 union all
select 2101, 'גרוסמן מאיר', null, 1 union all
select 2102, 'קורקידי', null, 1 union all
select 2103, 'שיק', null, 1 union all
select 2104, 'צונץ', null, 1 union all
select 2105, 'רח 3385', null, 1 union all
select 2106, 'כרמי דב', null, 1 union all
select 2107, 'אזור תעשיה הירקון', null, 1 union all
select 2108, 'הזז חיים', null, 1 union all
select 2109, 'רוזן פנחס', null, 1 union all
select 2110, 'הלוחמים', null, 1 union all
select 2111, 'רמבה אייזיק', null, 1 union all
select 2112, 'דריוס מיו', null, 1 union all
select 2113, '3946', null, 1 union all
select 2114, '3947', null, 1 union all
select 2115, 'יוניצ''מן', null, 1 union all
select 2116, 'מיכאל (נאמן)', null, 1 union all
select 2117, 'רח 2040', null, 1 union all
select 2118, 'אורי צבי גרינברג', null, 1 union all
select 2119, 'גרינברג אורי צבי', null, 1 union all
select 2120, 'יערי מאיר', null, 1 union all
select 2121, 'גלילי ישראל', null, 1 union all
select 2122, 'בוני העיר', null, 1 union all
select 2123, 'רובינא חנה', null, 1 union all
select 2124, 'קובנר אבא', null, 1 union all
select 2125, 'רופא המחתרות', null, 1 union all
select 2126, 'רובין ראבן', null, 1 union all
select 2127, 'רובין ראובן', null, 1 union all
select 2128, 'אביגור שאול', null, 1 union all
select 2129, 'מרסל ינקו', null, 1 union all
select 2130, 'ויינשל', null, 1 union all
select 2131, 'רוזנבלום יאיר', null, 1 union all
select 2132, 'סמבורסקי דניאל', null, 1 union all
select 2133, 'מוקדי משה', null, 1 union all
select 2134, 'רח 2632', null, 1 union all
select 2135, 'רח 3632', null, 1 union all
select 2136, 'רח 4632', null, 1 union all
select 2137, 'סאמט שמעון', null, 1 union all
select 2138, 'רח 0212', null, 1 union all
select 2139, 'רח 0402', null, 1 union all
select 2140, 'סי אנד סאן', null, 1 union all
select 2141, 'קאונטרי קלאב', null, 1 union all
select 2142, 'סמ גולי קניה', null, 1 union all
select 2143, 'סוסקין אברהם', null, 1 union all
select 2144, 'לבון פנחס', null, 1 union all
select 2145, 'ירבלום מרק', null, 1 union all
select 2146, 'גוטמן נחום', null, 1 union all
select 2147, 'מעבר 333', null, 1 union all
select 2148, 'רח 553', null, 1 union all
select 2149, 'רח 653', null, 1 union all
select 2150, 'רח 824', null, 1 union all
select 2151, 'רח 924', null, 1 union all
select 2152, 'רח 044', null, 1 union all
select 2153, 'רח 443', null, 1 union all
select 2154, 'רח 444', null, 1 union all
select 2155, 'רח 454', null, 1 union all
select 2156, 'רח 074', null, 1 union all
select 2157, 'רח 974', null, 1 union all
select 2158, 'רח 985', null, 1 union all
select 2159, 'רח 316', null, 1 union all
select 2160, 'רח 416', null, 1 union all
select 2161, 'רח 516', null, 1 union all
select 2162, 'רח 236', null, 1 union all
select 2163, 'רח 666', null, 1 union all
select 2164, 'רח 866', null, 1 union all
select 2165, 'רח 396', null, 1 union all
select 2166, 'רח 796', null, 1 union all
select 2167, 'רח 117', null, 1 union all
select 2168, 'רח 818', null, 1 union all
select 2169, 'רח 658', null, 1 union all
select 2170, 'רח 709', null, 1 union all
select 2171, 'רח 219', null, 1 union all
select 2172, 'רח 129', null, 1 union all
select 2173, 'רח 679', null, 1 union all
select 2174, 'רח 779', null, 1 union all
select 2175, 'רח 979', null, 1 union all
select 2176, 'רח 089', null, 1 union all
select 2177, 'רח 1019', null, 1 union all
select 2178, 'רח 4201', null, 1 union all
select 2179, 'יעוד ודרך', null, 1 union all
select 2180, 'רח 3601', null, 1 union all
select 2181, 'רח 3701', null, 1 union all
select 2182, 'רח 0801', null, 1 union all
select 2183, 'רח 1081', null, 1 union all
select 2184, 'רח 6901', null, 1 union all
select 2185, 'רח 9901', null, 1 union all
select 2186, 'רח 0011', null, 1 union all
select 2187, 'רח 3011', null, 1 union all
select 2188, 'רח 4011', null, 1 union all
select 2189, 'רח 5011', null, 1 union all
select 2190, 'רח 6011', null, 1 union all
select 2191, 'רח 7011', null, 1 union all
select 2192, 'רח 8011', null, 1 union all
select 2193, 'רח 2111', null, 1 union all
select 2194, 'סמ בארי', null, 1 union all
select 2195, 'רח 5111', null, 1 union all
select 2196, 'רח 6111', null, 1 union all
select 2197, 'רח 8111', null, 1 union all
select 2198, 'רח 1211', null, 1 union all
select 2199, 'רח 0311', null, 1 union all
select 2200, 'רח 1311', null, 1 union all
select 2201, 'רח 1133', null, 1 union all
select 2202, 'רח 4963', null, 1 union all
select 2203, 'רח 8311', null, 1 union all
select 2204, 'רח 9311', null, 1 union all
select 2205, 'רח 0411', null, 1 union all
select 2206, 'רח 1411', null, 1 union all
select 2207, 'רח 2411', null, 1 union all
select 2208, 'צימפל פרידריך', null, 1 union all
select 2209, 'אליאש מרים', null, 1 union all
select 2210, 'רח 6611', null, 1 union all
select 2211, 'אליאב בנימין', null, 1 union all
select 2212, 'רח 8611', null, 1 union all
select 2213, 'סילמן יהודה קדיש', null, 1 union all
select 2214, 'שוהם צילה', null, 1 union all
select 2215, 'סלע עמנואל', null, 1 union all
select 2216, 'רח 4711', null, 1 union all
select 2217, 'רח 9711', null, 1 union all
select 2218, 'רח 3811', null, 1 union all
select 2219, 'רח 6811', null, 1 union all
select 2220, 'רח 1191', null, 1 union all
select 2221, 'זיע"א יוסף חיים', null, 1 union all
select 2222, 'רח 3911', null, 1 union all
select 2223, 'רח 4911', null, 1 union all
select 2224, 'חדד סעדיא', null, 1 union all
select 2225, 'חלד יוסף', null, 1 union all
select 2226, 'סחרוב אנדרי', null, 1 union all
select 2227, 'יששכרוב חי', null, 1 union all
select 2228, 'מייטוס אליהו', null, 1 union all
select 2229, 'רח 2021', null, 1 union all
select 2230, 'מוהר יחיאל', null, 1 union all
select 2231, 'לוי משה אהרון', null, 1 union all
select 2232, 'אנוסי משהד', null, 1 union all
select 2233, 'רח 6021', null, 1 union all
select 2234, 'גסטר משה', null, 1 union all
select 2235, 'ונטורה משה', null, 1 union all
select 2236, 'רח 1209', null, 1 union all
select 2237, 'רח 0121', null, 1 union all
select 2238, 'כ"ץ בן ציון', null, 1 union all
select 2239, 'הופמן יעקב', null, 1 union all
select 2240, 'בור נילס', null, 1 union all
select 2241, 'גרשום שלום', null, 1 union all
select 2242, 'רח 5121', null, 1 union all
select 2243, 'בלומנפלד יהודה', null, 1 union all
select 2244, 'גורלסקי ברוך', null, 1 union all
select 2245, 'הלוי ז''ק', null, 1 union all
select 2246, 'מילר כהן אניטה', null, 1 union all
select 2247, 'רח 0221', null, 1 union all
select 2248, 'רח 1221', null, 1 union all
select 2249, 'רח 3221', null, 1 union all
select 2250, 'רח 4321', null, 1 union all
select 2251, 'רח 5321', null, 1 union all
select 2252, 'רח 6321', null, 1 union all
select 2253, 'רח 7321', null, 1 union all
select 2254, 'רח 1238', null, 1 union all
select 2255, 'רח 4384', null, 1 union all
select 2256, 'רח 7384', null, 1 union all
select 2257, 'צ''רטוק שמשון', null, 1 union all
select 2258, 'רח 8802', null, 1 union all
select 2259, 'רח 1239', null, 1 union all
select 2260, 'רח 0421', null, 1 union all
select 2261, 'הרב באזוב דוד', null, 1 union all
select 2262, 'רח 7421', null, 1 union all
select 2263, 'רח 9421', null, 1 union all
select 2264, 'רח 1252', null, 1 union all
select 2265, 'רח 1253', null, 1 union all
select 2266, 'רח 1254', null, 1 union all
select 2267, 'חכם שמעון', null, 1 union all
select 2268, 'פילץ אריה', null, 1 union all
select 2269, 'שרמן משה', null, 1 union all
select 2270, 'בן דוד חיים', null, 1 union all
select 2271, 'רח 8621', null, 1 union all
select 2272, 'צ''רצ''יל וינסטון', null, 1 union all
select 2273, 'אלטמן אריה', null, 1 union all
select 2274, 'רח 2721', null, 1 union all
select 2275, 'רח 3721', null, 1 union all
select 2276, 'רח 0821', null, 1 union all
select 2277, 'מוסינזון יגאל', null, 1 union all
select 2278, 'רח 7484', null, 1 union all
select 2279, 'רח 3002', null, 1 union all
select 2280, 'אוניקובסקי פרץ', null, 1 union all
select 2281, 'רח 8002', null, 1 union all
select 2282, 'קהילת זגלביה', null, 1 union all
select 2283, 'רח 2096', null, 1 union all
select 2284, 'רח 1312', null, 1 union all
select 2285, 'ברתנא מרדכי', null, 1 union all
select 2286, 'רח 9312', null, 1 union all
select 2287, 'רח 0412', null, 1 union all
select 2288, 'אויסטרך דויד', null, 1 union all
select 2289, 'רח 9712', null, 1 union all
select 2290, 'דר'' לוין שלום', null, 1 union all
select 2291, 'לוין שלום', null, 1 union all
select 2292, 'רח'' 2281', null, 1 union all
select 2293, 'רח 5811', null, 1 union all
select 2294, 'רח 1193', null, 1 union all
select 2295, 'רח 8193', null, 1 union all
select 2296, 'רח 9193', null, 1 union all
select 2297, 'רח 0293', null, 1 union all
select 2298, 'רח 1293', null, 1 union all
select 2299, 'רח 2293', null, 1 union all
select 2300, 'רח 3293', null, 1 union all
select 2301, 'רח 2368', null, 1 union all
select 2302, 'שוסטקוביץ דימיטרי', null, 1 union all
select 2303, '4216', null, 1 union all
select 2304, 'רוזנבלום הרצל', null, 1 union all
select 2305, 'גלבלום אריה', null, 1 union all
select 2306, 'רח 4850', null, 1 union all
select 2307, 'העדני מהלל', null, 1 union all
select 2308, 'מהלל העדני', null, 1 union all
select 2309, 'קדמוני אסא', null, 1 union all
select 2310, 'רח 9484', null, 1 union all
select 2311, 'אלבז נתן', null, 1 union all
select 2312, 'רח 4878', null, 1 union all
select 2313, 'רח 4880', null, 1 union all
select 2314, 'רח 0024', null, 1 union all
select 2315, 'גז מטילדה', null, 1 union all
select 2316, 'רח 0093', null, 1 union all
select 2317, 'רח 0132', null, 1 union all
select 2318, 'ד"ר פלד רות', null, 1 union all
select 2319, 'ד"ר פלד רות רופין', null, 1 union all
select 2320, 'רח 0283', null, 1 union all
select 2321, 'רח 0313', null, 1 union all
select 2322, 'שינדלר אוסקר', null, 1 union all
select 2323, 'פוחובסקי אריה', null, 1 union all
select 2324, 'פוחובסקי אריה דר''', null, 1 union all
select 2325, 'רח 0384', null, 1 union all
select 2326, 'רח 0422', null, 1 union all
select 2327, 'רכטר זאב', null, 1 union all
select 2328, 'רח 0484', null, 1 union all
select 2329, 'רח 0512', null, 1 union all
select 2330, 'רח 0583', null, 1 union all
select 2331, 'תבין אלי', null, 1 union all
select 2332, 'רח 0683', null, 1 union all
select 2333, 'רח 0684', null, 1 union all
select 2334, 'רח 0712', null, 1 union all
select 2335, 'רח 0783', null, 1 union all
select 2336, 'רח 0784', null, 1 union all
select 2337, 'רח 2132', null, 1 union all
select 2338, 'רח 0883', null, 1 union all
select 2339, 'רח 0921', null, 1 union all
select 2340, 'גלבוע אמיר', null, 1 union all
select 2341, 'רח 2290', null, 1 union all
select 2342, 'רח 0973', null, 1 union all
select 2343, 'דולצ''ין אריה', null, 1 union all
select 2344, 'רח 1093', null, 1 union all
select 2345, 'פרידמן שרגא', null, 1 union all
select 2346, 'רח 1222', null, 1 union all
select 2347, 'עמירן עמנואל', null, 1 union all
select 2348, 'רח 1283', null, 1 union all
select 2349, 'חזן יעקב', null, 1 union all
select 2350, 'פלדרמן וילהלם', null, 1 union all
select 2351, 'פלדרמן וילהלם דר''', null, 1 union all
select 2352, 'רח 3831', null, 1 union all
select 2353, 'רח 1384', null, 1 union all
select 2354, 'רח 1484', null, 1 union all
select 2355, 'רח 1583', null, 1 union all
select 2356, 'רח 1683', null, 1 union all
select 2357, 'וקנין רפי', null, 1 union all
select 2358, 'צלאן פאול', null, 1 union all
select 2359, 'רח 1783', null, 1 union all
select 2360, 'שדמי נחום', null, 1 union all
select 2361, 'רח 3281', null, 1 union all
select 2362, 'הייקל יוסף', null, 1 union all
select 2363, 'רח 1884', null, 1 union all
select 2364, 'רח 1921', null, 1 union all
select 2365, 'רח 2291', null, 1 union all
select 2366, 'שגאל מרק', null, 1 union all
select 2367, 'רח 2024', null, 1 union all
select 2368, 'רח 2032', null, 1 union all
select 2369, 'רח 2093', null, 1 union all
select 2370, 'אלי כהן', null, 1 union all
select 2371, 'כהן אלי', null, 1 union all
select 2372, 'ארצי יצחק', null, 1 union all
select 2373, 'קיסרי אורי', null, 1 union all
select 2374, 'רח 2263', null, 1 union all
select 2375, 'רח 2283', null, 1 union all
select 2376, 'רח 2322', null, 1 union all
select 2377, 'רח 2324', null, 1 union all
select 2378, 'סגל שמוליק', null, 1 union all
select 2379, 'רח 2383', null, 1 union all
select 2380, 'רח 2384', null, 1 union all
select 2381, '4897', null, 1 union all
select 2382, 'בילויה מעוז', null, 1 union all
select 2383, 'רח 2484', null, 1 union all
select 2384, 'רח 2513', null, 1 union all
select 2385, 'לבני איתן', null, 1 union all
select 2386, 'אקסלרוד נתן', null, 1 union all
select 2387, 'רח 2663', null, 1 union all
select 2388, 'רח 2683', null, 1 union all
select 2389, 'רח 2684', null, 1 union all
select 2390, 'רח 2712', null, 1 union all
select 2391, 'קריגר משה', null, 1 union all
select 2392, 'רח 2783', null, 1 union all
select 2393, 'רח 2784', null, 1 union all
select 2394, 'רח 2822', null, 1 union all
select 2395, 'רינהרט מקס', null, 1 union all
select 2396, 'רח 4882', null, 1 union all
select 2397, 'רח 2921', null, 1 union all
select 2398, 'זינגר בשביס יצחק', null, 1 union all
select 2399, 'רח 3024', null, 1 union all
select 2400, 'רח 3032', null, 1 union all
select 2401, 'רח 3122', null, 1 union all
select 2402, 'בן גל מיכאל', null, 1 union all
select 2403, 'בן גל(דג''מס)מיכאל', null, 1 union all
select 2404, 'רח 3322', null, 1 union all
select 2405, 'זליבנסקי', null, 1 union all
select 2406, 'זליבנסקי דוד הלוי', null, 1 union all
select 2407, 'רח 3384', null, 1 union all
select 2408, 'רח 3484', null, 1 union all
select 2409, 'רח 3513', null, 1 union all
select 2410, 'סשא ארגוב', null, 1 union all
select 2411, 'סשה ארגוב', null, 1 union all
select 2412, 'רח 3683', null, 1 union all
select 2413, 'רח 3684', null, 1 union all
select 2414, 'כהן יעקב', null, 1 union all
select 2415, 'רח 3783', null, 1 union all
select 2416, 'רח 3784', null, 1 union all
select 2417, 'רח 3843', null, 1 union all
select 2418, 'רח 3883', null, 1 union all
select 2419, 'רח 3884', null, 1 union all
select 2420, 'רח 3921', null, 1 union all
select 2421, 'רח 3922', null, 1 union all
select 2422, 'רח 4032', null, 1 union all
select 2423, 'פיינברג יוסף', null, 1 union all
select 2424, 'רח'' 2314', null, 1 union all
select 2425, 'רח 4132', null, 1 union all
select 2426, 'רח 8884', null, 1 union all
select 2427, 'ברסקי יהודה לייב', null, 1 union all
select 2428, 'רח 4303', null, 1 union all
select 2429, 'רח 4322', null, 1 union all
select 2430, 'פינקל שמעון', null, 1 union all
select 2431, 'רח 1832', null, 1 union all
select 2432, 'וילנסקי משה', null, 1 union all
select 2433, 'רח 4584', null, 1 union all
select 2434, 'רח 4683', null, 1 union all
select 2435, 'הרב צוברי יוסף', null, 1 union all
select 2436, 'פרנץ קפקא', null, 1 union all
select 2437, 'רח 4783', null, 1 union all
select 2438, 'רח 2184', null, 1 union all
select 2439, 'יהודה עמיחי ', null, 1 union all
select 2440, 'רח 4884', null, 1 union all
select 2441, 'רח 4921', null, 1 union all
select 2442, 'רח 4922', null, 1 union all
select 2443, 'רח 4953', null, 1 union all
select 2444, 'רח 5032', null, 1 union all
select 2445, 'רח 5124', null, 1 union all
select 2446, 'איתין אהרון', null, 1 union all
select 2447, 'רח 5163', null, 1 union all
select 2448, 'רח 5222', null, 1 union all
select 2449, 'פוירשטיין אמיל', null, 1 union all
select 2450, 'רח 5284', null, 1 union all
select 2451, 'רח 5322', null, 1 union all
select 2452, 'זמיר עמנואל', null, 1 union all
select 2453, 'רח 5384', null, 1 union all
select 2454, 'מרידור יעקב', null, 1 union all
select 2455, 'רח 4845', null, 1 union all
select 2456, 'לוין קיפניס', null, 1 union all
select 2457, 'קיפניס לוין', null, 1 union all
select 2458, 'זעירא מרדכי', null, 1 union all
select 2459, 'רח 5683', null, 1 union all
select 2460, 'רח 5684', null, 1 union all
select 2461, 'גלעזר אליהו', null, 1 union all
select 2462, 'רח 5783', null, 1 union all
select 2463, 'דר'' שבי יעקב מאור', null, 1 union all
select 2464, 'ש"בי יעקב מאור', null, 1 union all
select 2465, 'רח 5812', null, 1 union all
select 2466, 'אייזק שטרן', null, 1 union all
select 2467, 'רח 5884', null, 1 union all
select 2468, 'רח 5922', null, 1 union all
select 2469, 'רח 596', null, 1 union all
select 2470, 'רח 5983', null, 1 union all
select 2471, 'רח 6032', null, 1 union all
select 2472, 'אידלסון רחל ושמוא', null, 1 union all
select 2473, 'ע הלל', null, 1 union all
select 2474, 'ע.הלל', null, 1 union all
select 2475, 'רח 6284', null, 1 union all
select 2476, 'שמאלי אליעזר', null, 1 union all
select 2477, 'הופנקו משה', null, 1 union all
select 2478, 'הרמלין יוסף', null, 1 union all
select 2479, 'רח 6533', null, 1 union all
select 2480, 'רח 6583', null, 1 union all
select 2481, 'רח 4856', null, 1 union all
select 2482, 'רח 6614', null, 1 union all
select 2483, 'בן חיים פאול', null, 1 union all
select 2484, 'יוחננוף כהן שמואל', null, 1 union all
select 2485, 'רח 4822', null, 1 union all
select 2486, 'רוזנשטיין אברהם', null, 1 union all
select 2487, 'רח 6783', null, 1 union all
select 2488, 'סנהדראי טובה', null, 1 union all
select 2489, 'רח 6821', null, 1 union all
select 2490, 'רח 2286', null, 1 union all
select 2491, 'ריבולוב מנחם', null, 1 union all
select 2492, 'רח 6922', null, 1 union all
select 2493, 'רח 6983', null, 1 union all
select 2494, 'רח 7032', null, 1 union all
select 2495, 'רח 6884', null, 1 union all
select 2496, 'רח 7122', null, 1 union all
select 2497, 'משה (שלוש)', null, 1 union all
select 2498, 'רח 7183', null, 1 union all
select 2499, 'רח 7224', null, 1 union all
select 2500, 'ויטנברג יצחק', null, 1 union all
select 2501, 'ויטנברג לאו יצחק', null, 1 union all
select 2502, 'רח 7284', null, 1 union all
select 2503, 'אריה שרון אדר''', null, 1 union all
select 2504, 'שרון אריה', null, 1 union all
select 2505, 'רח 7383', null, 1 union all
select 2506, 'זק"ש נלי', null, 1 union all
select 2507, 'קול משה', null, 1 union all
select 2508, 'רח 7583', null, 1 union all
select 2509, 'רח 7584', null, 1 union all
select 2510, 'אלמוג דוד', null, 1 union all
select 2511, 'אורלוב חנה', null, 1 union all
select 2512, 'רח 7773', null, 1 union all
select 2513, 'רח 7783', null, 1 union all
select 2514, 'רח 7784', null, 1 union all
select 2515, 'רח 2287', null, 1 union all
select 2516, 'שטרייכמן יחזקאל', null, 1 union all
select 2517, 'רח 7922', null, 1 union all
select 2518, 'רח 7983', null, 1 union all
select 2519, 'רח 8024', null, 1 union all
select 2520, 'רח 8032', null, 1 union all
select 2521, 'איזמוז''יק לאה ודו', null, 1 union all
select 2522, 'איזמוזי''ק לאה ודו', null, 1 union all
select 2523, 'רח 8183', null, 1 union all
select 2524, 'רח 8222', null, 1 union all
select 2525, 'רח 8224', null, 1 union all
select 2526, 'ברוידס אברהם', null, 1 union all
select 2527, 'רח 8284', null, 1 union all
select 2528, 'רח 8383', null, 1 union all
select 2529, 'רח 8384', null, 1 union all
select 2530, 'נרקיס עוזי', null, 1 union all
select 2531, 'רח 8483', null, 1 union all
select 2532, 'רח 8514', null, 1 union all
select 2533, 'רח 8583', null, 1 union all
select 2534, 'רח 8584', null, 1 union all
select 2535, 'מאור משה', null, 1 union all
select 2536, 'רח 8673', null, 1 union all
select 2537, 'ברלין ישעיהו', null, 1 union all
select 2538, 'רח 8684', null, 1 union all
select 2539, 'רח 8783', null, 1 union all
select 2540, 'רח 8812', null, 1 union all
select 2541, 'רח 8821', null, 1 union all
select 2542, 'רובינשטיין ארתור', null, 1 union all
select 2543, 'רח 2288', null, 1 union all
select 2544, 'רח 8922', null, 1 union all
select 2545, 'רח 8983', null, 1 union all
select 2546, 'רח 9022', null, 1 union all
select 2547, 'רח 9032', null, 1 union all
select 2548, 'וינשטיין נחום', null, 1 union all
select 2549, 'רח 9163', null, 1 union all
select 2550, 'רח 9203', null, 1 union all
select 2551, 'רח 9213', null, 1 union all
select 2552, 'רח 9222', null, 1 union all
select 2553, 'אברך ישעיהו', null, 1 union all
select 2554, 'רח 9243', null, 1 union all
select 2555, 'ויטלה מאוריציו', null, 1 union all
select 2556, 'מאוריציו ויטלה', null, 1 union all
select 2557, 'פרלשטיין יצחק', null, 1 union all
select 2558, 'רח 9384', null, 1 union all
select 2559, 'מקס ברוד', null, 1 union all
select 2560, 'רח 9584', null, 1 union all
select 2561, 'רח 9612', null, 1 union all
select 2562, 'פרייגרזון צבי', null, 1 union all
select 2563, 'רח 9684', null, 1 union all
select 2564, 'רח 9783', null, 1 union all
select 2565, 'אונטרמן איסר יהוד', null, 1 union all
select 2566, 'אונטרמן אסר יהודה', null, 1 union all
select 2567, 'רח 9821', null, 1 union all
select 2568, 'חפץ ישה', null, 1 union all
select 2569, 'רח 2289', null, 1 union all
select 2570, 'רח 9873', null, 1 union all
select 2571, 'רח 4889', null, 1 union all
select 2572, 'רח 9922', null, 1 union all
select 2573, 'רח 9983', null, 1 union all
select 2574, 'ארסטידס סוזה מנדס', null, 1 union all
select 2575, 'יעקב שבתאי', null, 1 union all
select 2576, '2244', null, 1 union all
select 2577, 'רח מ"ה', null, 1 union all
select 2578, 'פרלוק משה', null, 1 union all
select 2579, 'רח 9224', null, 1 union all
select 2580, 'רח 6224', null, 1 union all
select 2581, 'רח 0324', null, 1 union all
select 2582, 'זריצקי יוסף', null, 1 union all
select 2583, 'רח 7821', null, 1 union all
select 2584, 'פן אלכסנדר', null, 1 union all
select 2585, 'מאייר מרדכי', null, 1 union all
select 2586, 'בקר אהרון', null, 1 union all
select 2587, 'מילוא יוסף', null, 1 union all
select 2588, 'שניצר שמואל', null, 1 union all
select 2589, 'פאגלין עמיחי', null, 1 union all
select 2590, 'ברלין אליהו', null, 1 union all
select 2591, 'סטימצקי', null, 1 union all
select 2592, 'זליגמן מקס', null, 1 union all
select 2593, 'אבידן דוד', null, 1 union all
select 2594, 'רח 1032', null, 1 union all
select 2595, 'רח 1132', null, 1 union all
select 2596, 'סמ אלון', null, 1 union all
select 2597, 'דבורה', null, 1 union all
select 2598, 'תמיר שמואל', null, 1 union all
select 2599, 'רח 5632', null, 1 union all
select 2600, 'רח 0032', null, 1 union all
select 2601, 'רח 2280', null, 1 union all
select 2602, 'רח'' 2280', null, 1 union all
select 2603, '4865', null, 1 union all
select 2604, 'מנוי ברשת בזק', null, 1 union all
select 2605, 'רח בזק', null, 1 union all
select 2606, 'רח 2292', null, 1 union all
select 2607, '3866', null, 1 union all
select 2608, '3867', null, 1 union all
select 2609, '3868', null, 1 union all
select 2610, 'שד'' מיכאל נאמן', null, 1 union all
select 2611, 'רח 5822', null, 1 union all
select 2612, 'ככר ב'' בנובמבר', null, 1 union all
select 2613, 'ככר הכנסת', null, 1 union all
select 2614, 'ככר ביאליק', null, 1 union all
select 2615, 'ככר דיזנגוף', null, 1 union all
select 2616, 'ככר הבימה', null, 1 union all
select 2617, 'ככר ההסתדרות', null, 1 union all
select 2618, 'ככר היל', null, 1 union all
select 2619, 'ככר ברנשטין לאונר', null, 1 union all
select 2620, 'ככר המדינה', null, 1 union all
select 2621, 'ככר המושבות', null, 1 union all
select 2622, 'ככר המלך אלברט', null, 1 union all
select 2623, 'ככר הסוכנות', null, 1 union all
select 2624, 'ככר השוטר', null, 1 union all
select 2625, 'ככר חסידי האומות', null, 1 union all
select 2626, 'ככר לונדון', null, 1 union all
select 2627, 'ככר מגן דוד', null, 1 union all
select 2628, 'ככר מיכאלס', null, 1 union all
select 2629, 'ככר נמיר', null, 1 union all
select 2630, 'ככר פלומר', null, 1 union all
select 2631, 'ככר קדומים', null, 1 union all
select 2632, 'ככר שטרן מרדכי', null, 1 union all
select 2633, 'ככר מהלר גוסטב', null, 1 union all
select 2634, 'ככר יצחק רבין', null, 1 union all
select 2635, 'ככר גרשוין ג''ורג''', null, 1 union all
select 2636, 'ככר סתר מרדכי', null, 1 union all
select 2637, 'ככר אופנבך ז''ק', null, 1 union all
select 2638, 'ככר בלוך ארנסט', null, 1 union all
select 2639, 'ככר וולך יונה', null, 1 union all
select 2640, 'ככר שנברג ארנולד', null, 1 union all
select 2641, 'רחבת לאונרד ברנשט', null, 1 union all
select 2642, 'הבלונים', null, 1 union all
select 2643, 'אזורי חן', null, 1 union all
select 2644, 'קרית החינוך', null, 1 union all
select 2645, 'שכ כוכב הצפון', null, 1 union all
select 2646, 'תכנית ל', null, 1 union all
select 2647, 'יפו העתיקה', null, 1 union all
select 2648, 'שכ שפירא', null, 1 union all
select 2649, 'שכ מונטיפיורי', null, 1 union all
select 2650, 'שכ יד אליהו', null, 1 union all
select 2651, 'שכ ביצרון', null, 1 union all
select 2652, 'שכ התקווה', null, 1 union all
select 2653, 'גני יהושע', null, 1 union all
select 2654, 'ש לדוגמא', null, 1 union all
select 2655, 'ש לדוגמא ב', null, 1 union all
select 2656, 'ש נוה אביבים', null, 1 union all
select 2657, 'מרכז הירידים', null, 1 union all
select 2658, 'ש רמת אביב', null, 1 union all
select 2659, 'ש אפקה', null, 1 union all
select 2660, 'שכ גלילות', null, 1 union all
select 2661, 'שכ שיך מוניס', null, 1 union all
select 2662, 'רמת אביב החדשה', null, 1 union all
select 2663, 'גבעת הפרחים', null, 1 union all
select 2664, 'שכ פלורנטין', null, 1 union all
select 2665, 'שכ רביבים', null, 1 union all
select 2666, 'ש הדר יוסף', null, 1 union all
select 2667, 'ש מחל', null, 1 union all
select 2668, 'ש מעוז אביב', null, 1 union all
select 2669, 'ש עולי צכיה', null, 1 union all
select 2670, 'שכ תל ברוך', null, 1 union all
select 2671, 'המשתלה', null, 1 union all
select 2672, 'נווה דן', null, 1 union all
select 2673, 'מע יד המעביר', null, 1 union all
select 2674, 'ש דן', null, 1 union all
select 2675, 'ש יוגוסלבים', null, 1 union all
select 2676, 'ש ישגב', null, 1 union all
select 2677, 'ש מעונות', null, 1 union all
select 2678, 'ש נוה משכן', null, 1 union all
select 2679, 'ש נוה שרת', null, 1 union all
select 2680, 'גני צהלה', null, 1 union all
select 2681, 'שכ נחלת יצחק', null, 1 union all
select 2682, 'ש צהלה', null, 1 union all
select 2683, 'ש שנחאי', null, 1 union all
select 2684, 'שכ גן הירקון', null, 1 union all
select 2685, 'קרית עתידים', null, 1 union all
select 2686, 'רמות צהלה', null, 1 union all
select 2687, 'שכ מחלול א', null, 1 union all
select 2688, 'שכ מחלול ב', null, 1 union all
select 2689, 'מרכז רפואי סוראסק', null, 1 union all
select 2690, 'שכ נורדיה', null, 1 union all
select 2691, 'ש בבלי', null, 1 union all
select 2692, 'שכ גב עמל ב', null, 1 union all
select 2693, 'עג''מי', null, 1 union all
select 2694, 'שכ גב עמל א', null, 1 union all
select 2695, 'שכ כ סומיל', null, 1 union all
select 2696, 'כרם התימנים', null, 1 union all
select 2697, 'בית יעקב', null, 1 union all
select 2698, 'שכ ולהלה', null, 1 union all
select 2699, 'שכ חסן בק', null, 1 union all
select 2700, 'תל חיים', null, 1 union all
select 2701, 'שכ נווה צדק', null, 1 union all
select 2702, 'הרה"ג יוסף צוברי', null, 1 union all
select 2703, 'הקריה', null, 1 union all
select 2704, 'שכ הרכבת', null, 1 union all
select 2705, 'גבעת הרצל', null, 1 union all
select 2706, 'שכ מכבי ישנה', null, 1 union all
select 2707, 'שכ קזנובה', null, 1 union all
select 2708, 'שכ שפת הים', null, 1 union all
select 2709, 'ש חסכון כביש בת י', null, 1 union all
select 2710, 'ש עממי שד ירושלים', null, 1 union all
select 2711, 'ש צהלון', null, 1 union all
select 2712, 'שכ שבת', null, 1 union all
select 2713, 'גבעת התמרים', null, 1 union all
select 2714, 'שכ אבו כביר', null, 1 union all
select 2715, 'ש חסכון יפו', null, 1 union all
select 2716, 'ש סחנה א', null, 1 union all
select 2717, 'שכון ד', null, 1 union all
select 2718, 'שכ נוה שאנן', null, 1 union all
select 2719, 'שכ ראשלצ', null, 1 union all
select 2720, 'שכ גב משה א', null, 1 union all
select 2721, 'שכ מכבי חדשה', null, 1 union all
select 2722, 'שכ עובד', null, 1 union all
select 2723, 'שכ שיבת ציון', null, 1 union all
select 2724, 'נוה תקוה', null, 1 union all
select 2725, 'ש סלע ק שלום', null, 1 union all
select 2726, 'ש צבא קבע ק שלום', null, 1 union all
select 2727, 'ש קרית שלום', null, 1 union all
select 2728, 'שכ שמעון', null, 1 union all
select 2729, 'ש מגורים ב', null, 1 union all
select 2730, 'ש רמת ישראל', null, 1 union all
select 2731, 'רמת הטייסים', null, 1 union all
select 2732, 'ש הקאוקזים', null, 1 union all
select 2733, 'ש נוה צהל', null, 1 union all
select 2734, 'שכ גב אלישיב', null, 1 union all
select 2735, 'מע ב כ שלם', null, 1 union all
select 2736, 'שכ גב שמשון', null, 1 union all
select 2737, 'שכ הארגזים', null, 1 union all
select 2738, 'שכ הבולגרים', null, 1 union all
select 2739, 'שכ ידידיה', null, 1 union all
select 2740, 'שכ לבנה', null, 1 union all
select 2741, 'שכ עזרא', null, 1 union all
select 2742, 'כפר שלם', null, 1 union all
select 2743, 'מע א כ שלם', null, 1 union all
select 2744, 'נוה אליעזר', null, 1 union all
select 2745, 'נוה ברבור', null, 1 union all
select 2746, 'נוה כפיר', null, 1 union all
select 2747, 'ניר אביב', null, 1 union all
select 2748, 'ש נוה שלם', null, 1 union all
select 2749, 'סיטי מנשיה', null, 1 union all
select 2750, 'אזור הספורט', null, 1 union all
select 2751, 'שכ גן ההגנה', null, 1 union all
select 2752, 'רח 6273', null, 1 union all
select 2753, 'רח'' 2285', null, 1 union all
select 2754, 'רח'' 2284', null, 1 union all
select 2755, 'שאגל מרק', null, 1 union all
select 2756, 'דה פיליפ אדיס (אב', null, 1 union all
select 2757, 'רח'' 3813', null, 1 union all
select 2758, 'מוזיאון הארץ', null, 1 union all
select 2759, 'רציף 0', null, 1 union all
select 2760, 'רציף 1', null, 1 union all
select 2761, 'רציף 2', null, 1 union all
select 2762, 'רציף 3', null, 1 union all
select 2763, 'רציף 4', null, 1 union all
select 2764, 'רציף 5', null, 1 union all
select 2765, 'רציף 6', null, 1 union all
select 2766, 'חוף הילטון', null, 1 union all
select 2767, 'מלון מנדרין', null, 1 union all
select 2768, 'חוף הצוק', null, 1 union all
select 2769, 'חוף שרתון', null, 1 union all
select 2770, 'חוף תל ברוך', null, 1 union all
select 2771, 'מגרשי התערוכה', null, 1 union all
select 2772, 'אצטדיון בלומפילד', null, 1 union all
select 2773, 'חוף בוגרשוב', null, 1 union all
select 2774, 'קרית התערוכות', null, 1 union all
select 2775, 'מרינה ת"א', null, 1 union all
select 2776, 'קרית האוניברסיטה', null, 1 union all
select 2777, 'פארק דרום', null, 1 union all
select 2778, 'קרוואנים ק.שלום', null, 1 union all
select 2779, 'קרוואנים שלבים', null, 1 union all
select 2780, 'חוף ירושלים', null, 1 union all
select 2781, 'חוף גאולה', null, 1 union all
select 2782, 'חוף הגולשים', null, 1 union all
select 2783, 'רח'' 4101', null, 1 union all
select 2784, 'רח'' 2243', null, 1 union all
select 2785, 'רח'' 2244', null, 1 union all
select 2786, 'תב"ע 1116', null, 1 union all
select 2787, 'רח מא שכ'' הארגזים', null, 1 union all
select 2788, 'התחנה', null, 1 union all
select 2789, 'רח'' 4850', null, 1 union all
select 2790, 'רח'' 2367', null, 1 union all
select 2791, 'רח'' 4849', null, 1 union all
select 2792, '1206', null, 1 union all
select 2793, 'רח'' נמל ת"א', null, 1 union all
select 2794, 'רח 2080', null, 1 union all
select 2795, '2חוף מציצים', null, 1 union all
select 2796, 'נרדי נחום', null, 1 union all
select 2797, 'אופיר שייקה', null, 1 union all
select 2798, 'בריג אמיל', null, 1 union all
select 2799, 'גילוץ דבורה ומנחם', null, 1 union all
select 2800, 'מחפוז נג''יב', null, 1 union all
select 2801, 'אבן חלדון', null, 1 union all
select 2802, 'טאג''יר שמואל וסול', null, 1 union all
select 2803, 'אבולעפיה רבקה ושל', null, 1 union all
select 2804, 'יהושע רוזין', null, 1 union all
select 2805, 'זאבי רחבעם (גנדי)', null, 1 union all
select 2806, 'מבוא גורוכוב', null, 1 union all
select 2807, 'יקותיאלי יוסף', null, 1 union all
select 2808, 'מהלר גוסטב', null, 1 union all
select 2809, 'רח'' 2283', null, 1;